### ISSUE TITLE
(24449) TypeError: Cannot read property 'Value' of undefined

### ISSUE THREAD

**Issue by Starter4711** [iobroker-community-adapters/ioBroker.fronius#116]
**Describe the bug**  
Fehlermeldung: 

fronius.0 | 2021-05-02 14:00:21.249 | warn | (24449) TypeError: Cannot read property 'Value' of undefined
-- | -- | -- | --

Alles Stable, aktuell.

**Comment by nkleber78** [comment]
Duplikat von #76. Bitte testen und Ticket schließen wenn das so passt

**Comment by Starter4711** [comment]
Hallo, sehe nicht was ich testen soll?

**Comment by nkleber78** [comment]
Installation der letzen version von meinem Repository oder warten bis die Version offiziell released wird. Da leider keine Versionsinformationen von deiner Seite vorhanden sind wissen wir auch nicht was du für einen Stand hast
Ich denke es wird bald ein neues Stable release geben...

**Comment by Starter4711** [comment]
Version 1.0.5 (stable)

**Comment by mcm1957** [comment]
Duplikat von https://github.com/iobroker-community-adapters/ioBroker.fronius/issues/76.
