### ISSUE TITLE
[Lösung]Adapter findet keine Verbindung zum Gerät - obwohl alles i.O ist

### ISSUE THREAD

**Issue by Fiiti** [iobroker-community-adapters/ioBroker.fronius#126]
Ich hatte nach einer Nigel Nagel neuen Installation via Proxmox auf Ubuntu 21.04 das Problem, dass die fronius-Instanz nur 2 von 3 Grün hatte. Der unterste - Verbindung zum Gerät - war immer rot.
Mit Debug im Protokoll gesehen, dass er pingt:

`2021-06-05 12:51:06.701 | debug | System command: /bin/ping -n -w2 -c1 192.168.1.190`

/bin/ping ist aber im default nur  für sudu erlaubt, hier schien das Problem zu sein.

Ein 
sudo chmod u+s \`which ping\`  
reichte aus, damit alles wieder lief.

Keine Ahnung, ob das vom Adapter kommt oder von iobroker.
Ist auch egal, evtl. hilft es den einem oder anderen.

Fii

**Comment by Negalein** [comment]
> sudo chmod u+s `which ping`
> reichte aus, damit alles wieder lief.
> 
> Keine Ahnung, ob das vom Adapter kommt oder von iobroker.
> Ist auch egal, evtl. hilft es den einem oder anderen.


Danke für den Tipp!!
Jetzt ist er wieder grün! 👍
