### ISSUE TITLE
Neuste stable von Januar 2018 - neuere stable?

### ISSUE THREAD

**Issue by m4ding** [iobroker-community-adapters/ioBroker.fronius#128]
Hallo,

vielleicht eine blöde Frage: ich setze in iobroker auf das stable repo. Die letzte stable zu diesem Adapter ist von Januar 2018 (1.0.5). Gibt es Pläne, eine neuere Version als stable zu markieren?

Danke und Grüsse 
mading

**Comment by mcm1957** [comment]
Aktuelle stable = aktuell latest = 1.1.3 v 15.03.2021 08:22:15

v2.0.0 ist in Arbiet
