### ISSUE TITLE
State "fronius.0.inverter.1.UAC_L3" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by homecineplexx** [iobroker-community-adapters/ioBroker.fronius#129]
Version 1.1.6

some warnings:
`

fronius.0 | 2021-07-27 12:00:18.825 | warn | State "fronius.0.inverter.1.UAC_L3" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
fronius.0 | 2021-07-27 12:00:18.824 | warn | State "fronius.0.inverter.1.UAC_L2" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-07-27 12:00:18.823 | warn | State "fronius.0.inverter.1.UAC_L1" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-07-27 12:00:18.822 | warn | State "fronius.0.inverter.1.IAC_L3" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-07-27 12:00:18.821 | warn | State "fronius.0.inverter.1.IAC_L2" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-07-27 12:00:18.819 | warn | State "fronius.0.inverter.1.IAC_L1" has no existing object, this might lead to an error in future versions

`

**Comment by mcm1957** [comment]
https://github.com/iobroker-community-adapters/ioBroker.fronius/issues/206
