### ISSUE TITLE
No values for Meter

### ISSUE THREAD

**Issue by chrineuh** [iobroker-community-adapters/ioBroker.fronius#151]
Hello, 

I have yesterday install  a new version of Iobroker. 

I dont have used the restore feature because i wantet to get an new clean system (i had a lot of problems with the old ) 

So i have installet the the latest fronus adapter version but there are no objekts for the meter only the Inverter. 

Look this is the new system : 

![image](https://user-images.githubusercontent.com/60777681/134803085-19a40947-d550-4b7e-b83b-cf12c8b185ee.png)

and this was the old : 

![image](https://user-images.githubusercontent.com/60777681/134803113-45b15ec1-c414-4e33-bb42-04d14870bea0.png)

at both system is the verson 1.1.3 

old system : 

![image](https://user-images.githubusercontent.com/60777681/134803151-cd832a71-c24e-4fbe-9caf-4d558f7d22a8.png)

new system : 
![image](https://user-images.githubusercontent.com/60777681/134803172-455475e3-7278-4d38-8b0a-3f6b54d7fbf2.png)

**Comment by mcm1957** [comment]
Screenshot of new system die not show any installed instance. So I guess something was gone wrong during installation.

If the problem still occures with the actual release please open a new issue.
