### ISSUE TITLE
Sensorbox Daten werden nicht angezeigt

### ISSUE THREAD

**Issue by doemb33** [iobroker-community-adapters/ioBroker.fronius#152]
Adapter liefert keine Werte der Sensorbox
![Screenshot 2021-09-28 at 15-16-16 objects - Stand-PC(SmartHome)](https://user-images.githubusercontent.com/91131026/135094400-881e6ec4-198b-49ee-9b9d-9136a098b468.png)

![grafik](https://user-images.githubusercontent.com/91131026/135094646-c55967e3-0954-447e-b5ea-af48c17ae0a9.png)
![grafik](https://user-images.githubusercontent.com/91131026/135096504-4d6a786d-0851-4fee-a5a8-2a657b8a15e2.png)

Hallo miteinander,

ich bin neu hier und ersuche um Hilfe.
mache ich was falsch, dass ich die Werte der Sensorbox nicht bekomme oder ist meine Vermutung richtig, dass diese Werte noch keiner gebraucht hat.

![grafik](https://user-images.githubusercontent.com/91131026/135095846-77acc4e6-8eb1-42a1-8ebd-c0b086aa0755.png)

LG Johannes

**Comment by nkleber78** [comment]
@doemb33 Du hast leider recht, die Sensordaten hat bisher keiner gebraucht und somit sind zwar die Strukturen eingefügt, aber nicht die entsprechenden Datenpunkte. Wenn du uns eine Beschreibung liefern kannst welche daten du genau benötigst, dann kann ich mir das mal in nächster Zeit anschauen wie hoch der  Aufwand dafür ist. Wenn du mit automatisch generierten Datenpunkten zufrieden bist, dann geht das ggf. relativ einfach. Allerdings sind dann alle daten vom typ "mixed", und der Name und die Beschreibung entsprechen dem Text der auf der API geliefert wird und Einheit gibt es nicht. Das hab ich bereits für den Meter so implementiert als fallback...

**Comment by nkleber78** [comment]
Btw. Da ich keine Sensorbox habe, bitte den response von folgenden API calls hier als file anhängen 
GetSensorRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=NowSensorData bzw. 
GetSensorRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=MinMaySensorData

**Comment by doemb33** [comment]
[Bedienungsanleitung Fronius Solar API V1a.pdf](https://github.com/iobroker-community-adapters/ioBroker.fronius/files/7245757/Bedienungsanleitung.Fronius.Solar.API.V1a.pdf)
[GetSensorRealtimeData.cgi.json.txt](https://github.com/iobroker-community-adapters/ioBroker.fronius/files/7245802/GetSensorRealtimeData.cgi.json.txt)
[GetSensorRealtimeDataMinMax.cgi.json.txt](https://github.com/iobroker-community-adapters/ioBroker.fronius/files/7245806/GetSensorRealtimeDataMinMax.cgi.json.txt)
Hallo Norbert,

anbei wie gewünscht; die automatisch generierten Datenpunkte sollten reichen.

Danke im voraus

LG Johannes

**Comment by nkleber78** [comment]
Implementierung ist in V2.0.0
