### ISSUE TITLE
Nach Firmware Update GEN24 - 1.13.13-1 Warnmeldungen

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.fronius#153]
Gestern gab es von Fronius ein Firmware Update den GEN24 Wechselrichter. Seit diesem Update tauchen im LOG die folgenden Meldungen auf ( Adapter Version 1.1.6)

`
<html>
<body>

fronius.0 | 2021-09-30 07:28:21.594 | warn | (7796) State "fronius.0.meter.0.TimeStamp" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
fronius.0 | 2021-09-30 07:28:21.435 | warn | (7796) State "fronius.0.powerflow.Meter_Location" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:28:01.539 | warn | (7796) State "fronius.0.powerflow.Meter_Location" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:28:01.460 | warn | (7796) State "fronius.0.meter.0.TimeStamp" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:27:41.635 | warn | (7796) State "fronius.0.powerflow.Meter_Location" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:27:41.538 | warn | (7796) State "fronius.0.meter.0.TimeStamp" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:27:21.516 | warn | (7796) State "fronius.0.meter.0.TimeStamp" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:27:21.424 | warn | (7796) State "fronius.0.powerflow.Meter_Location" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:27:01.522 | warn | (7796) State "fronius.0.powerflow.Meter_Location" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:27:01.439 | warn | (7796) State "fronius.0.meter.0.TimeStamp" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:26:41.547 | warn | (7796) State "fronius.0.powerflow.Meter_Location" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:26:41.545 | warn | (7796) State "fronius.0.meter.0.TimeStamp" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:26:21.589 | warn | (7796) State "fronius.0.meter.0.TimeStamp" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:26:21.481 | warn | (7796) State "fronius.0.powerflow.Meter_Location" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:26:01.542 | warn | (7796) State "fronius.0.meter.0.TimeStamp" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:26:01.436 | warn | (7796) State "fronius.0.powerflow.Meter_Location" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:25:41.552 | warn | (7796) State "fronius.0.meter.0.TimeStamp" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:25:41.442 | warn | (7796) State "fronius.0.powerflow.Meter_Location" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:25:21.531 | warn | (7796) State "fronius.0.powerflow.Meter_Location" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:25:21.527 | warn | (7796) State "fronius.0.meter.0.TimeStamp" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:25:01.516 | warn | (7796) State "fronius.0.meter.0.TimeStamp" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:25:01.415 | warn | (7796) State "fronius.0.powerflow.Meter_Location" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:24:41.544 | warn | (7796) State "fronius.0.powerflow.Meter_Location" has no existing object, this might lead to an error in future versions
fronius.0 | 2021-09-30 07:24:41.543 | warn | (7796) State "fronius.0.meter.0.TimeStamp" has no existing object, this might lead to an error in future versions

</body>
</html>`

Zur Info das Change Log des Firmware Update.

> 1.1 Fronius Symo GEN24 6.0 - 10.0 / Symo GEN24 3.0 – 5.0
1.1.1 Bundle 1.13.13-1
Software-Version: 1.13.13-1
Steuerung Core 1.10.11-1
Steuerung Control 0.6.7-1
Steuerung Webseite des
Wechselrichters
1.10.9-0
Leistungsteil Kronos 2.22.6-12544
Leistungsteil Zeus 2.15.4-6887
Leistungsteil Rhea 2.6.1
Neue Funktionen:
/ Phasengenaue Einspeisebegrenzung („weakest phase approach“) als eigener Mode einstellbar
/ Solar API Anpassungen laut API Dokumentation
/ Fernsteuerung über Solar Web implementiert. Im Web UI unter Kommunikation kann man nun die
Fernsteuerung via Solar Web aktivieren. Diese Funktion gibt den EVUs die Möglichkeit, die
Einspeisebegrenzung des Wechselrichters wenn nötig zu ändern (derzeit nur in Australien verwendet).
/ Neue Fehlercodes für Hardwaredefekt bei der AC Brückenschaltung.
State 1065 für L1, 1066 für L2 und 1068 für L3 wurden hinzugefügt
/ DC Summenstrombegrenzung zur Erhöhung der Lebensdauer bei bestimmten Arbeitspunkten. (Geringe DC
Spannung auf PV1,PV2 und BAT - Hoher DC Strom, hohe Temperaturen)
I_sum= I_PV1+ I_PV2+ I_BAT
1pNext 6kW: I_sum= 39A
1pNext 10kW: I_sum= 46A
3pNext 5kW: I_sum= 30A
3pNext 10kW: I_sum= 50A
Bugfixes:
/ Fehlauslösungen State 1048 (= AC Überstrom) wurden behoben.
/ Neutralleiterbrucherkennung im Notstrom wurde behoben. Bisher keine Detektion im Fehlerfall vom Gerät.
/ Keine Batteriebewirtschaftung bei MPP Spannungen von 720VDC. Bei höheren MPP Spannungen konnte es
passieren dass teilweise die Batterie nicht bedient worden ist wenn zuerst PV und dann erst die BAT
eingeschaltet worden ist.
/ Keine Batteriebewirtschaftung wenn im laufenden Betrieb die Batterie manuell für >10min. abgeschaltet wird
und danach wieder eingeschaltet wird. Batterie startete dann im Energiesparmodus hoch. Bisher half hier nur
ein AC/DC Reset.
/ CAN Bus Fehlauslösungen (=State 1020 & State 1022) behoben
/ Modbus API via TCP funktionierte bei Austauschgeräten nicht
/ Lastmanagement Funktion – Automatische Korrektur bei der Funktion „Leistungsüberschuss“ nach einem
Software Update auf 1.13.9. Je nach Softwarestand waren die Bezugs und Einspeiseparameter genau
invertiert. (Sowohl auf der Web UI als auch bei Modbus/API Kommandos). Mit dem Update wird dies
automatisch richtig gestellt.
/ Web UI Funktion „Maßnahmen gegen FI-Fehlauslösungen“ hat nicht funktioniert
/ Vermeiden von FI Auslösungen beim Abschalten der BYD Batterie
/ Falscher Fehlercode im Falle einer Überlast im Notstrom. Bisher wurde teilweise nur ein Leistung zu niedrig
Fehler angezeigt anstatt Überlast Fehler.
/ State 1143 BugFix. Fehlauslösungen behoben
/ Cloud Handling BugFix: Geräte verbinden sich wieder automatisch mit Solar Web nach einem
Verbindungsverlust.
Änderungen in den Länder-Setups:
/ Australien Setupänderung AUS1 – AUS7 aufgrund AS 4777.2
/ Setup Adaption Switzerland (Typ A & Typ B)
/ Neues Setup ZA1 für Südafrika
/ Neues Setup IE hinzugefügt
/ Setup EE hinzugefügt (Estonia)
/ Setupänderung Setup SE – FAC Werte angepasst 
Text and illustrations technically correct at the time of going to print. Right to effect modifications is reserved. Fronius International GmbH, http://www.fronius.com
/ Neue Setups AUA, AUB und AUC für Australien & Setup NZ1 für Neuseeland

**Comment by Satmedia** [comment]
Kann ich bestätigen. Bekomme die gleichen Fehlermeldungen nach Gen24 FW Update.

Fronius Adapter Version 1.1.6

**Comment by nkleber78** [comment]
Einfach nur den Adapter neu starten. Dann werden die neuen Objekte angelegt. Damals musste ich einen ganzen Haufen neue Objekte anlegen da sie den Namen geändert hatten. Nun ist der name wieder zurück geändert worden... Leider muss man somit auch wieder die ganzen Objekte bzgl. logging ändern :-(

**Comment by JBSullivan** [comment]
@nkleber78  Du meinst sicher die Objekte löschen und dann über die Instanz neu erzeugen lassen - oder? 

Nur Start / Stop der Instanz habe ich schon gemacht. Das hat nichts geändert. Wie du schon sagst, leider muss man nach dem löschen des Objekt Baum das Loggin für jeden Datenpunkt wieder neu setzen und hoffen das man alle erwischt hat und keiner vergessen wurde.

Das ist in meinen Augen eine "Achillesferse" von ioB, das dass Loggin von DP`s bei einem erneuten erzeugen einer vorhandenen Instanz nicht wieder eingetragen werden. 

Vielleicht müsste man auf ioB Ebene dafür mal eine Funktion entwickeln, die einem in diesem Fall die Option offen läßt "alte" DP Log Einträge, wieder zu übernehmen oder zu entfernen, wenn ein Objekt Baum durch die Instanz neu erzeugt wurde.

**Comment by nkleber78** [comment]
@JBSullivan Ich meinte schon nur stop/start der Instanz. Dann legt er die objekte an, auch wenn im ersten schritt diese Warnungen angezeigt werden. 
Btw. Ich laufe auf Admin 5 mit der Version 1.1.6 von Github. Bei mir hat er nach dem Update einfach zuerst die Warnungen ausgegeben und dann aber auch die neuen Objekte angelegt. Natürlich bleibt das Problem des Mappings da sich leider die ID'd geändert haben...

**Comment by mcm1957** [comment]
see https://github.com/iobroker-community-adapters/ioBroker.fronius/issues/206
