### ISSUE TITLE
Fronius Adapter Warning solange keine Energie geliefert wird

### ISSUE THREAD

**Issue by Hard-n-Soft** [iobroker-community-adapters/ioBroker.fronius#168]
Hallo,

nachdem ich den ioBroker neu aufgesetzt habe und auch das Backup per FTP funktioniert ist nun auch der Fronius Adapter für den Gen24 Wechselrichter in Betrieb und liefert munter Daten solange die Sonne scheint. Abfrageinterval 10 Sekunden.

Außerhalb des Zeitraumes liefert der Adapter doch folgende Meldung und überschwemmt das Log

```
fronius.0 | 209780 | 2021-11-06 07:43:50.096 | warn | TypeError: Cannot read property 'Value' of undefined
fronius.0 | 209780 | 2021-11-06 07:43:40.110 | warn | TypeError: Cannot read property 'Value' of undefined
fronius.0 | 209780 | 2021-11-06 07:43:30.093 | warn | TypeError: Cannot read property 'Value' of undefined
fronius.0 | 209780 | 2021-11-06 07:43:20.095 | warn | TypeError: Cannot read property 'Value' of undefined
fronius.0 | 209780 | 2021-11-06 07:43:10.093 | warn | TypeError: Cannot read property 'Value' of undefined
fronius.0 | 209780 | 2021-11-06 07:43:00.094 | warn | TypeError: Cannot read property 'Value' of undefined
fronius.0 | 209780 | 2021-11-06 07:42:50.107 | warn | TypeError: Cannot read property 'Value' of undefined
fronius.0 | 209780 | 2021-11-06 07:42:40.111 | warn | TypeError: Cannot read property 'Value' of undefined

```
Ich denke sobald die PV Anlage Strom liefert und der Wechselrichter aktiv arbeitet kommt keine Fehlermeldung. Lässt sich da was machen?

Gruß Hard-n-Soft

**Comment by nkleber78** [comment]
Liegt vmtl. daran dass nicht die letzte Version installiert ist. Bei der 1.1.6 sollte das nicht auftreten, zumindest tritt es bei mir nicht auf

**Comment by Hard-n-Soft** [comment]
Hallo,
danke für die schnelle RM. Bezieht sich die 1.1.6 auf die Adapter Version? Bei mir steht als aktuelle die 1.0.5 zur Auswahl.

![ioBrokerFronius1](https://user-images.githubusercontent.com/59067955/140605088-c056a093-322d-40f9-b651-cfe9ac4d11f2.jpg)

**Comment by nkleber78** [comment]
Das ist leider nicht im Stable Channel. Du musst also auf den Beta wechseln und dann Updaten… oder direkt von GitHub

**Comment by mcm1957** [comment]
Dürfte in 2.0.0 behoben sein.
zu testen ,..

**Comment by mcm1957** [comment]
Kein (negatives) Feedback - lets close here.
