### ISSUE TITLE
kein storage in den objekten

### ISSUE THREAD

**Issue by sjfm-design** [iobroker-community-adapters/ioBroker.fronius#175]
mein problem ist, daß wenn ich höher als v1.0.5 gehe, dann bekomm ich storage nicht mehr in den objekten.
sobald ich wieder auf v1.0.5 down gehe, ist storage wieder da.
![1](https://user-images.githubusercontent.com/30467409/145692842-25c1bb53-f5ef-4e0d-bce4-7f249c5d9bd6.png)
![2](https://user-images.githubusercontent.com/30467409/145692844-c024c714-96c5-4791-8f36-3051b42044d8.png)

**Comment by nkleber78** [comment]
Integriert in der V2.0.0
