### ISSUE TITLE
State "fronius.0.inverter.1.FAC" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by firex2** [iobroker-community-adapters/ioBroker.fronius#176]
Ich habe den Fronius Symo GEN24 10.0 Plus und bekomme sehr oft die Meldung `State "fronius.0.inverter.1.FAC" has no existing object, this might lead to an error in future versions`. Habe den Adapter schon neu gestartet, hat nicht geholfen. Was kann ich da tun?

![grafik](https://user-images.githubusercontent.com/2738065/145965195-63e76919-bbea-42d3-9c90-95c62ca0a3ef.png)

**Comment by maloross** [comment]
Bei mir hat dieser DP und noch ein paar andere ebenfalls gefehlt. Ich habe die fehlenden DP selbst erstellt ( im Expertenmodus, DP als Zahl definiert). Sofort wurden auch Werte eingetragen
`{
  "common": {
    "name": "FAC",
    "desc": "Manuell erzeugt",
    "role": "state",
    "type": "number",
    "read": true,
    "write": true,
    "def": ""
  },
  "type": "state",
  "_id": "fronius.0.inverter.1.FAC",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1643716695085
}`

Bis jetzt alles ok, werde aber nach demnächst mal schauen, ob nach Systemneustart (oder Adapter-Update) die selbst erstellt DP auch bleiben ;)

**Comment by mcm1957** [comment]
see https://github.com/iobroker-community-adapters/ioBroker.fronius/issues/206
