### ISSUE TITLE
Warning for future versions

### ISSUE THREAD

**Issue by homecineplexx** [iobroker-community-adapters/ioBroker.fronius#201]
In v1.1.3 there always comes this message

`State "fronius.0.inverter.1.Power_DC_String_2" has no existing object, this might lead to an error in future versions`

**Comment by mcm1957** [comment]
@nkleber78 
Alle states müssen vor dem Beschreiben angelegt werden.

**Comment by nkleber78** [comment]
Objekte werden vorher angelegt. In seltenen fällen kann es aber dazu kommen dass das Anlegen noch nicht im System übernommen wurde.
