### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.fronius#22]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.fronius

- [x] [E106] Title should not have word "adapter" in the name. It is clear, that this is adapter. Now: Fronius inverters adapter

ERR:["E106"]:ERR

Thanks,
your automatic adapter checker.

**Comment by ldittmar81** [comment]
fixed wuth commit https://github.com/iobroker-community-adapters/ioBroker.fronius/commit/2b7714ab4fe5de442b95911f7a0a73537ab5d37d

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
