### ISSUE TITLE
Nach Austausch von neuem Smartmeter keine Werte mehr im Objektbaum "meter"

### ISSUE THREAD

**Issue by nikmaier** [iobroker-community-adapters/ioBroker.fronius#242]
Hallo,
gestern ist mein altes Fronius Smartmeter v63 gegen ein neues v65 ausgetauscht worden, beim alten hatte ich immer diese Datenpunkte:

![1](https://user-images.githubusercontent.com/69574329/179918080-881ed03f-fa1a-441e-ade2-1737390fb9b9.JPG)

Das neue Smartmeter wird anscheinend nicht erkannt, hier habe ich unter dem Objektbaum "meter" keine Daten:

![2](https://user-images.githubusercontent.com/69574329/179918198-c4b7d8e4-e032-4ae0-b656-b12fd4e91737.jpg)

Gibt es hier eine Lösung?

Danke im Voraus.

**Comment by nkleber78** [comment]
@nikmaier Existiert das Problem noch? Falls ja bitte mehr details um dies zu reproduzieren. Bitte auch den API output anhängen. Entweder ist die Adresse anders oder es kommen generell keine Daten...

**Comment by nikmaier** [comment]
Hallo, ja das ist immer noch nach wie vor vorhanden, kommen keinerlei Daten vom neuen Smartmeter.
Was genau brauchst du? Was meinst du mit API output?

**Comment by nkleber78** [comment]
Adapter version?
Api output von http://192.168.0.1/solar_api/v1/GetMeterRealtimeData.cgi?Scope=Device&DeviceId=0
Object data von diesem Objekt system.adapter.fronius.0 wobei die ID am schluß mit deiner Instanz zusammenpassen muss

Danke

**Comment by nikmaier** [comment]
Adapter: 1.1.6:
![image](https://github.com/iobroker-community-adapters/ioBroker.fronius/assets/69574329/e1922fe4-c407-408f-ab23-6da5423696cd)

Aber wo finde ich die richtige Device-ID?

**Comment by nkleber78** [comment]
http://192.168.0.1/solar_api/v1/GetActiveDeviceInfo.cgi?DeviceClass=System Da findest du deine device informationen. Bitte schick mir auch davon den response

**Comment by nikmaier** [comment]
Also hier der erste response, hab mal die S/N weg:

`{
   "Body" : {
      "Data" : {
         "Inverter" : {
            "1" : {
               "DT" : 1,
               "Serial" : "3310xx"
            }
         },
         "Meter" : {
            "1" : {
               "DT" : -1,
               "Serial" : "271xx"
            }
         },
         "Ohmpilot" : {},
         "Storage" : {
            "0" : {
               "DT" : -1,
               "Serial" : "P030T020Z22xxx     "
            }
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DeviceClass" : "System"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2023-06-04T10:11:21+00:00"
   }
}`

Und hier dann der zweite, aber hier kommt nichts, ich muss doch als ID die Seriennummer vom Meter nehmen oder:

`{
   "Body" : {
      "Data" : {}
   },
   "Head" : {
      "RequestArguments" : {
         "DeviceId" : "2717xx",
         "Scope" : "Device"
      },
      "Status" : {
         "Code" : 12,
         "Reason" : "Meter '2717xx' does not exist.",
         "UserMessage" : ""
      },
      "Timestamp" : "2023-06-04T10:12:44+00:00"
   }
}`

**Comment by nkleber78** [comment]
Für den 2. response musst du hier die ID  des  meters nehmen und nicht die Sn. D.h. in deinem fall 1. bitte auch noch die Adapter config. Ich vermute dass in deiner adapter config die ID 0 drin steht und nicht 1... Offensichtlich hat sich hier die ID auf der API geändert mit dem neuen Smartmeter. Hast du schon mal checkIP gedrückt in der Instanz Konfiguration? 
![image](https://github.com/iobroker-community-adapters/ioBroker.fronius/assets/35381530/707b6752-43c3-4c46-b2f1-c4e7f50ad74d)

**Comment by nikmaier** [comment]
Ah wahnsinn, ich hab mal Check Ip gedrückt und dann nochmal gespeichert.
Jetzt hat er mir tatsächlich unter meter einen neuen Ordner mit der Nummer 1, also quasi die ID1 gemacht. 
Und dort ist jetzt alles drin.
Es kann so einfach sein *lol*

Vielen lieben Dank für deine Hilfe und diesen Tip!

**Comment by nkleber78** [comment]
Sehr gut. 
Problem behoben, wird dann in der V2.0.0 dann auch zyklisch gemacht (Prüfung ob neue Geräte am Bus). Daher wird das ticket geschlossen
