### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.fronius#25]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.fronius

- [ ] [E145] No news found for actual version 1.1.6
- [ ] [E154] common.dependencies must contain{"js-controller": ">=2.0.0"} or {"js-controller": ">=3.0.0"}
- [ ] [E504] found setInterval in "main.js, but no clearInterval detected
- [ ] [E605] No actual year found in copyright. Please add "Copyright (c) 2022 ldittmar <iobroker@lmdsoft.de>" at the end of README.md
- [ ] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 ldittmar <iobroker@lmdsoft.de>" at the start of LICENSE

Thanks,
your automatic adapter checker.

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by mcm1957** [comment]
obsolete - will be checked with 2.0.0 release building anyway

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
