### ISSUE TITLE
Update Intervall Datenpunkte fronius.0.inverter

### ISSUE THREAD

**Issue by skyx3** [iobroker-community-adapters/ioBroker.fronius#254]
**Describe the bug**  
Nicht alle Datenpunkte werden gemäß Einstellung aktuallisiert. Das Update Intervall steht auf 10sec. Das funktioniert auch. Die folgenden Datenpunkt werden allerdings nur alle paar Minuten aktuallisiert. Gelierfert werden die Daten am Wechselrichter im Sekundentakt, also müssten sie eigentlich auch live verfügbar sein.

Folgende Datenpunkte sind betroffen:
fronius.0.inverter.1.Power_DC_String_1
fronius.0.inverter.1.Power_DC_String_2
fronius.0.inverter.1.Voltage_DC_String_1
fronius.0.inverter.1.Voltage_DC_String_2

**Versions:**  
 - Adapter version: 1.1.6
 - JS-Controller version: 4.0.23
 - Node version: 16.17.1
 - Operating system: Ubuntu

**Comment by skyx3** [comment]
Vielen Dank für das Feedback, das ist schade, verstehe nicht warum Fronius das nicht in Echtzeit zur Verfügung stellt. Eine Frage noch, auch wenn ich auf 60sec stelle, werden die Datenpunkte teilweise nur alls 3 bis 5min aktuallisiert.

**Comment by mcm1957** [comment]
@nkleber78 
Kannst du das ev. beantworten und dann den issue schließen bitte?

**Comment by nkleber78** [comment]
@skyx3 Falls das tatsächlich bei dir immer noch auftritt, dann bitte etwas mehr details wann bzw. wie das auftritt

**Comment by skyx3** [comment]
@nkleber78 Sprich ich soll einmal die neue Alpha Version testen, ob es dort nun behoben ist?

**Comment by nkleber78** [comment]
Wenn es geht wäre es gut wenn du die Alpha  Version auf einer separaten Instanz testen könntest. Ich teste das auch bei mir… hast du ev. Aufgezeichnete Daten für diese Parameter wo man sieht wie sie aktualisiert werden?

**Comment by nkleber78** [comment]
Btw. hab gerade nochmals meinen Response angeschaut. Dort kommen nur 5min daten. Wenn du einen Weg gefunden hast die DC string/tracker werte schneller abzuholen dann baue ich das gerne mit ein... Anbei ein Response von meinem Inverter. Da sieht man die Zeitstempel im intervall von 300sec

{"Current_DC_String_1":{"Unit":"A","Values":{"19500":0,"19800":0,"20100":0,"20400":0,"20700":0,"21000":0,"21300":0,"21600":0,"21900":0,"22200":0,"22500":0,"22800":0,"23100":0,"23400":0,"23700":0,"24000":0,"24300":0,"24600":0,"24900":0,"25200":0,"25500":0,"25800":0,"26100":0,"26400":0,"26700":0,"27000":0,"27300":0,"27600":0,"27900":0,"28200":0,"28500":0,"28800":0,"29100":0,"29400":0,"29700":0,"30000":0,"30300":0,"30600":0,"30900":0,"31200":0,"31500":0},"_comment":"channelId=66050"},"Current_DC_String_2":{"Unit":"A","Values":{"19500":0,"19800":0,"20100":0.12,"20400":0,"20700":0.26,"21000":0.36,"21300":0.48,"21600":0.59,"21900":0.63,"22200":0.62,"22500":0.64,"22800":0.67,"23100":0.7000000000000001,"23400":0.73,"23700":0.76,"24000":0.81,"24300":0.86,"24600":0.93,"24900":0.97,"25200":0.9500000000000001,"25500":1.03,"25800":1.18,"26100":1.24,"26400":1.29,"26700":1.34,"27000":1.3900000000000001,"27300":1.44,"27600":1.51,"27900":1.6300000000000001,"28200":1.86,"28500":2.21,"28800":2.5100000000000002,"29100":2.62,"29400":2.57,"29700":2.35,"30000":2.05,"30300":1.87,"30600":1.78,"30900":1.76,"31200":1.75,"31500":1.76},"_comment":"channelId=131586"},"Temperature_Powerstage":{"Unit":"°C","Values":{"19800":0,"20100":28,"20400":0,"20700":29,"21000":30,"21300":31,"21600":31,"21900":31,"22200":31,"22500":32,"22800":32,"23100":32,"23400":33,"23700":33,"24000":33,"24300":33,"24600":33,"24900":34,"25200":34,"25500":34,"25800":34,"26100":34,"26400":35,"26700":35,"27000":35,"27300":35,"27600":35,"27900":36,"28200":36,"28500":36,"28800":36,"29100":35,"29400":35,"29700":35,"30000":35,"30300":36,"30600":36,"30900":36,"31200":36,"31500":36},"_comment":"channelId=65795"},"Voltage_DC_String_1":{"Unit":"V","Values":{"19500":54.6,"19800":99.60000000000001,"20100":97.4,"20400":111.7,"20700":102.2,"21000":102.5,"21300":104.2,"21600":105,"21900":105.10000000000001,"22200":104.60000000000001,"22500":104.7,"22800":105.2,"23100":105.9,"23400":106.2,"23700":106.4,"24000":106.60000000000001,"24300":106.7,"24600":107.2,"24900":107.30000000000001,"25200":107.4,"25500":107.7,"25800":108.2,"26100":108.4,"26400":108.5,"26700":108.80000000000001,"27000":108.9,"27300":108.9,"27600":109.10000000000001,"27900":109.2,"28200":110,"28500":110.7,"28800":111,"29100":110.80000000000001,"29400":110.7,"29700":110.10000000000001,"30000":108.80000000000001,"30300":107.4,"30600":107.2,"30900":107.2,"31200":107.10000000000001,"31500":107.10000000000001},"_comment":"channelId=66049"},"Voltage_DC_String_2":{"Unit":"V","Values":{"19500":402,"19800":627.1,"20100":571.9,"20400":672.4000000000001,"20700":583.8000000000001,"21000":597.8000000000001,"21300":607.5,"21600":614.9000000000001,"21900":613.4,"22200":611.7,"22500":611.1,"22800":615.3000000000001,"23100":618.9000000000001,"23400":621.3000000000001,"23700":621.5,"24000":623.1,"24300":623.4000000000001,"24600":627.5,"24900":627.2,"25200":628.3000000000001,"25500":629.4000000000001,"25800":633,"26100":633.4000000000001,"26400":635,"26700":635.4000000000001,"27000":637.4000000000001,"27300":636.4000000000001,"27600":638.1,"27900":638.1,"28200":643.9000000000001,"28500":647.3000000000001,"28800":649.5,"29100":647.5,"29400":648.1,"29700":643.1,"30000":636.1,"30300":627.3000000000001,"30600":627.4000000000001,"30900":627.2,"31200":625.7,"31500":626.7},"_comment":"channelId=131585"}}

**Comment by nkleber78** [comment]
@skyx3 Ticket geschlossen. Falls sich doch noch was ergibt bitte einfach nochmal melden
