### ISSUE TITLE
Bool-Werte als common-type boolean speichern

### ISSUE THREAD

**Issue by Steff42** [iobroker-community-adapters/ioBroker.fronius#255]
Hallo,

aktuell werden bool-Werte als common-type mixed gespeichert. Wäre es möglich diese als common-type boolean zu speichern?
Des betrifft aktuell die z.B. die beiden Objekte:

`fronius.0.powerflow.BackupMode`
`fronius.0.powerflow.BatteryStandby`

Gruß Steffen

**Comment by nkleber78** [comment]
Das Thema ist, dass in vielen Fällen der Typ nicht erkannt werden kann und manchmal ist es sogar so dass sich die "Werte" ändern. In diesem fall sind die Parameter nicht gepflegt und daher werden sie default als mixed angelegt all fallback option. Es sollte aber problemlos sein wenn du den typ nachträglich auf Bool änderst...

**Comment by mcm1957** [comment]
Mein Input:
States sollten immer einen passenden Datentyp und soweit wie möglich eine passende role haben.
Dieser issue sollte noch mal genauer analysiert werden.

**Comment by Steff42** [comment]
Passt in Version 2.0.2

Gruß Steffen
