### ISSUE TITLE
Zweiter Smart Meter nicht sichtbar

### ISSUE THREAD

**Issue by dako0815** [iobroker-community-adapters/ioBroker.fronius#285]
Hallo,
ich habe an meinem Fronius Symo Hybrid einen zweiten Smart Meter angeschlossen der die Erzeugung eines weiteren Wechselrichters misst. Diesen sehe ich auch im Solarweb und die Erzeugung wird mir auch korrekt für beide angezeigt:
![image](https://user-images.githubusercontent.com/78207468/222969088-c0fb9f72-a54f-4b45-85c5-74f0d0be48c0.png)
![image](https://user-images.githubusercontent.com/78207468/222969118-ed82a6f7-7f1e-4658-af9d-1b2169cc49d3.png)

Über den Adapter bekomme ich aber nur den ersten SmartMeter übermittelt:
![image](https://user-images.githubusercontent.com/78207468/222969266-5e6dda77-77ca-479a-8abb-93068ea8f897.png)

Warum wird hier der zweite Fronius Smart Meter nicht mit angezeigt?

Grüße,
Daniel

**Comment by nkleber78** [comment]
@dako0815 Welche Version hast du installiert. Das sollte nun in der V2.0.0 gefixt sein. Wenn du ein Testsystem hast, dann gerne mal die Version 2.0.0 Alpha von GIT installieren und verifizieren

**Comment by nkleber78** [comment]
It is working on V2.0.1 on my test environment
