### ISSUE TITLE
[QA] eslint reports error at solarApiJson.js

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.fronius#300]
> eslint .

/home/runner/work/ioBroker.fronius/ioBroker.fronius/test/solarApiJson.js
  3:20  error  Parsing error: Unexpected token =

✖ 1 problem (1 error, 0 warnings)

-----

As an intermediate solution this file has been excluded from linting

**Comment by mcm1957** [comment]
In addition I would suggest to check whther this file could be migrated to a pure data file.
Currently it contains a class which exports several json strings referenced by variable names. It should be easy to migrate this to a pure json file read using require('filename')

**Comment by mcm1957** [comment]
I just fixed this issue.

plain variables at classes seems to be ruther new feature. So the eslint parser must be set to 2022 mode (was 2020 mode)
See https://stackoverflow.com/questions/60046847/eslint-does-not-allow-static-class-properties

I've fixed the other eslint issues like unneede escapes too.

This issue can be closed. No need to spent time to migrate to json file - unless you are interested for knowledge.

**Comment by nkleber78** [comment]
@mcm1957 i just did the move to the file. It is working. I also fixed the eslint issues with the hasOwnProperty as well

**Comment by mcm1957** [comment]
@nkleber78 
OK, thanks a lot. Thats (in my opinion) the cleanest solution - especially in reard of future maintanance.

**Comment by nkleber78** [comment]
But unfortunately this cases issues for the build as the folder is "test". Is there a way to make this import and the rest of the code only availlable when needed or ignore the "module not found" in case the module is not in test

**Comment by mcm1957** [comment]
Sorry for the late reply.

What kind of problems do you have?

I think one or more of the following should work:

-) you can move the solarApiJosn.json to lib directory. Its does not harm. And it would open the possibility to add a flag "testmode" to config to run the testmode at user systems too.

-) I do not see a reason why keeping the require inside the if statement just like curent code should not wiork. So the require will be executed only if configured in source

-) I assume require raises an exception if the file does notz exist. This could be cateched and ignored using try{} catch(e){} construct.

Please let me know if I can help more - feel free to ask at telegram as I will note this faster

**Comment by nkleber78** [comment]
can you help me by adding the testmode flag to the config. I think this is a good idea. I moved the JSON to the lib directory. I would propose to do a merge of the PR and adding the testmode to the config

**Comment by mcm1957** [comment]
For a first test please simply use a boolean variable (i.e. testMode) in main.js.
You can later set it by reading config.xxx. (But as far as I know there was some sort of such a variable anyway. But I did not scan last code)

**I will add the test flag when providing jsonConfig** as I cannot write (good) html / react code.

**Comment by nkleber78** [comment]
Perfect, it is already a variable in the code so we can use that later in the jsonConfig

**Comment by mcm1957** [comment]
fixed with 2.0.0-alpha.4
