### ISSUE TITLE
[QA] Perform ip / config check at adapter startup

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.fronius#306]
Please consider execution ip-check / retrieve-config call at startup of adapter.

This should avoid errors in case a user does not press "Checj-ip" button after changing config.

_Originally posted by @mcm1957 in https://github.com/iobroker-community-adapters/ioBroker.fronius/issues/305#issuecomment-1575523861_

**Comment by nkleber78** [comment]
Will be delivered in the next release

**Comment by mcm1957** [comment]
planned for 2.0.2
