### ISSUE TITLE
Values for I/O's

### ISSUE THREAD

**Issue by gemo-bi** [iobroker-community-adapters/ioBroker.fronius#333]
Is it possible that you can also see the status of the IO's or the status of the load management.

**Comment by mcm1957** [comment]
see https://github.com/iobroker-community-adapters/ioBroker.fronius/issues/123

I'm sorry, but this seems to be impossible.

Leaving Issue open for nkleber to correct if I'm wrong.

**Comment by gemo-bi** [comment]
too bad, would be cool for virtual relays...Am 17.07.2023 17:37 schrieb Kleber Norbert ***@***.***>:
Indeed i do not know a way how to achieve this except with Modbus TCP where you can use the Modbus Adapter
