### ISSUE TITLE
[Feature]  Werte der MPP auslesen.

### ISSUE THREAD

**Issue by Dreistein19** [iobroker-community-adapters/ioBroker.fronius#35]
Hallo,

Ich habe gelesen das du keinen Fronius mehr hast. Das macht die Entwicklung natürlich nicht einfacher.
Vielleicht ist aber doch möglich,  den Code so anzupassen das es möglich wird, 
die einzelnen "Strings" der Solaranlage auslesen zu können.
Bei uns ist es ein Primo 4.01 und wir haben "hinten" weniger Panels als "vorne".

**Comment by nkleber78** [comment]
Hallo @Dreistein19 
kannst du mir sagen von welchen Datenpunkten auf der SolarAPI du sprichst? Wenn die Daten auf der API verfügbar sind dann bitte hier die notwendigen Datenpunkte beschreiben. Dnke

**Comment by Dreistein19** [comment]
Hallo, leider weiß ich nicht ob die API die Werte überhaupt liefert. Ich frage sie per Modbus ab.

modbus.0.holdingRegisters.40282_1_DCA liefert z.b den Strom vom MPP 1.
modbus.0.holdingRegisters.40302_2_DCA z.B den Strom vom MPP2.

Damit kann man z.b. sehen wie bei einer Ost West Anlage die Stromerzeugung sich mit dem Sonnenstand ändert.
Ich finde das sehr Interessant.

**Comment by nkleber78** [comment]
Diese Datenpunkte solltest du über IDC und IDC_2 sowie UDC, UDC_2 bekommen und sind in der aktuellen Version enthalten...

**Comment by Dreistein19** [comment]
Leider liefert der Adapter diese Datenpunkte nicht. Ich habe einen Fronius Primo (Nur Wechselrichter).
Ich habe die Adapter Datenpunkte gelöscht und gehofft das die fehlenden Datenpunkte neu angelegt werden.
Leider nicht. 
Auch ein "händisches" Anlegen der Datenpunkte brachte keine Werte.
Mir ist auch aufgefallen, das bei einigen Datenpunkten keine "Units" (Maßeinheiten) angelegt werden.
Was ist z.b. der Punkt "DT" unter fronius.0.powerflow.inverter1.DT ?
MfG

**Comment by nkleber78** [comment]
Was der Primo kann, weiß ich nicht. Aber schau dir mal die Doku der solar API an. Dort werden die API calls sowie auch die Bedeutung der Datenpunkte beschrieben. https://www.fronius.com/~/downloads/Solar%20Energy/Operating%20Instructions/42%2C0410%2C2012.pdf Falls die datenpunkte tatsächlich verfügbar sind bei dir, dann schick mir deinen Output von http://deineIP/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DataCollection=CommonInverterData und schau ob du im Log warnungen erhälst. Aber ich denke dass dein Inverter das einfach nicht liefert. Wie gesagt, zuerst bitte schauen was bei dir über die API verfügbar ist...
Bzgl. Units: Jeden datenpunkt manuell anzulegen ist viel Aufwand, daher werden diese Automatisch erstellt, allerdings liefert die API die meisten units nicht. Diese müssen dann manuell nachgepflegt werden.

**Comment by Dreistein19** [comment]
Ich habe eben "mit Gewalt"  die Version 1.1.2 Installiert.  Die wurde mir irgendwie nicht als update von 1.1.1 angezeigt.
Ich habe dann eine Installation über die "Katze" durchgeführt.
Die Werte für die MPP 1&2 werden nun angezeigt.
Vielen Dank für deine Arbeit.

**Comment by pacco81** [comment]
Hi ! 
Bei mir läuft auch V1.1.2 vom Adapter und liest den Symo15 aus. Läuft super.

Die Archivdaten und insb. die Daten zu MPP 1&2 kommen bei mir aber leider nicht an.
@Dreistein19 : Wie sehen die Daten bei dir aus, wenn sie im iobroker ankommen ? Meine Objektliste sieht so aus:
<img width="722" alt="Bildschirmfoto 2021-03-14 um 10 02 58" src="https://user-images.githubusercontent.com/29131107/111062965-76f5e580-84ac-11eb-87e1-f538a0dac533.png">

Folgender Aufruf gibt die String-MPPT-Daten aus: `http://10.11.12.92/solar_api/v1/GetArchiveData.cgi?Scope=System&StartDate=13.3.2021&EndDate=13.3.2021&Channel=Current_DC_String_1&Channel=Current_DC_String_2`


{
	"Body" : 
	{
		"Data" : 
		{
			"inverter/1" : 
			{
				"Data" : 
				{
					"Current_DC_String_1" : 
					{
						"Unit" : "A",
						"Values" : 
						{
							"0" : 0,
							"10200" : 0,
							"10500" : 0,
							"10800" : 0,
							"11100" : 0,
							"11400" : 0,
							"11700" : 0,
							"1200" : 0,
							"12000" : 0,
							"12300" : 0,
							"12600" : 0,
							"12900" : 0,
							"13200" : 0,
							"13500" : 0,
							"13800" : 0,
							"14100" : 0,
							"14400" : 0,
							"14700" : 0,
							"1500" : 0,
							"15000" : 0,
							"15300" : 0,
							"15600" : 0,
							"15900" : 0,
							"16200" : 0,
							"16500" : 0,
							"16800" : 0,
							"17100" : 0,
							"17400" : 0,
							"17700" : 0,
							"1800" : 0,
							"18000" : 0,
							"18300" : 0,
							"18600" : 0,
							"18900" : 0,
							"19200" : 0,
							"19500" : 0,
							"19800" : 0,
							"20100" : 0,
							"20400" : 0,
							"20700" : 0,
							"2100" : 0,
							"21000" : 0,
							"21300" : 0,
							"21600" : 0,
							"21900" : 0,
							"22200" : 0,
							"22500" : 0,
							"22800" : 0,
							"23100" : 0,
							"23400" : 0,
							"23700" : 0,
							"2400" : 0,
							"24000" : 0,
							"24300" : 0,
							"24600" : 0,
							"24900" : 0,
							"25200" : 0,
							"25500" : 0,
							"25800" : 0.12,
							"26100" : 0.20999999999999999,
							"26400" : 0.31,
							"26700" : 0.47999999999999998,
							"2700" : 0,
							"27000" : 0.57000000000000006,
							"27300" : 0.64000000000000001,
							"27600" : 0.69000000000000006,
							"27900" : 0.67000000000000004,
							"28200" : 0.76000000000000001,
							"28500" : 0.65000000000000002,
							"28800" : 0.90000000000000002,
							"29100" : 1.1799999999999999,
							"29400" : 1.3300000000000001,
							"29700" : 1.52,
							"300" : 0,
							"3000" : 0,
							"30000" : 1.77,
							"30300" : 2,
							"30600" : 1.8200000000000001,
							"30900" : 2,
							"31200" : 2.1499999999999999,
							"31500" : 2.9199999999999999,
							"31800" : 3.2400000000000002,
							"32100" : 3.9100000000000001,
							"32400" : 4.2999999999999998,
							"32700" : 3.8599999999999999,
							"3300" : 0,
							"33000" : 3.8999999999999999,
							"33300" : 3.8000000000000003,
							"33600" : 3.6699999999999999,
							"33900" : 4,
							"34200" : 4,
							"34500" : 4.5600000000000005,
							"34800" : 6.0899999999999999,
							"35100" : 6.0099999999999998,
							"35400" : 6.0200000000000005,
							"35700" : 5.5200000000000005,
							"3600" : 0,
							"36000" : 5.2700000000000005,
							"36300" : 5.9299999999999997,
							"36600" : 5.3700000000000001,
							"36900" : 2.8199999999999998,
							"37200" : 1.26,
							"37500" : 1.9100000000000001,
							"37800" : 3.8900000000000001,
							"38100" : 3.4300000000000002,
							"38400" : 2.7400000000000002,
							"38700" : 1.98,
							"3900" : 0,
							"39000" : 1.47,
							"39300" : 1.29,
							"39600" : 1.8500000000000001,
							"39900" : 2.3900000000000001,
							"40200" : 2.3500000000000001,
							"40500" : 2.9900000000000002,
							"40800" : 3.1000000000000001,
							"41100" : 3.4399999999999999,
							"41400" : 3.5700000000000003,
							"41700" : 3.6200000000000001,
							"4200" : 0,
							"42000" : 3.9300000000000002,
							"42300" : 3.5800000000000001,
							"42600" : 3.0700000000000003,
							"42900" : 2.9900000000000002,
							"43200" : 3.29,
							"43500" : 3.3900000000000001,
							"43800" : 4.1299999999999999,
							"44100" : 6.3399999999999999,
							"44400" : 7.04,
							"44700" : 10.25,
							"4500" : 0,
							"45000" : 17.059999999999999,
							"45300" : 21.219999999999999,
							"45600" : 21.719999999999999,
							"45900" : 20,
							"46200" : 15.120000000000001,
							"46500" : 11.529999999999999,
							"46800" : 8.8000000000000007,
							"47100" : 10.359999999999999,
							"47400" : 7.1699999999999999,
							"47700" : 18.280000000000001,
							"4800" : 0,
							"48000" : 20.289999999999999,
							"48300" : 19.170000000000002,
							"48600" : 10.01,
							"48900" : 4.2599999999999998,
							"49200" : 3.1000000000000001,
							"49500" : 9.1300000000000008,
							"49800" : 12.870000000000001,
							"50100" : 5.1100000000000003,
							"50400" : 6.6400000000000006,
							"50700" : 11.59,
							"5100" : 0,
							"51000" : 15.93,
							"51300" : 11.16,
							"51600" : 13.050000000000001,
							"51900" : 6.6400000000000006,
							"52200" : 4.4400000000000004,
							"52500" : 14.33,
							"52800" : 18.969999999999999,
							"53100" : 14.609999999999999,
							"53400" : 18.57,
							"53700" : 16.899999999999999,
							"5400" : 0,
							"54000" : 14.640000000000001,
							"54300" : 19.289999999999999,
							"54600" : 16.75,
							"54900" : 11.98,
							"55200" : 4.7199999999999998,
							"55500" : 6.5200000000000005,
							"55800" : 9.7200000000000006,
							"56100" : 3.6699999999999999,
							"56400" : 7.0600000000000005,
							"56700" : 6.8799999999999999,
							"5700" : 0,
							"57000" : 5.4400000000000004,
							"57300" : 6.1799999999999997,
							"57600" : 2.2800000000000002,
							"57900" : 1.21,
							"58200" : 1.0600000000000001,
							"58500" : 1.3700000000000001,
							"58800" : 1.97,
							"59100" : 2.54,
							"59400" : 9.4000000000000004,
							"59700" : 8.1899999999999995,
							"600" : 0,
							"6000" : 0,
							"60000" : 6.4199999999999999,
							"60300" : 5.6600000000000001,
							"60600" : 5.1100000000000003,
							"60900" : 4.5700000000000003,
							"61200" : 4.0700000000000003,
							"61500" : 3.4199999999999999,
							"61800" : 3.21,
							"62100" : 2.6000000000000001,
							"62400" : 1.54,
							"62700" : 1.3800000000000001,
							"6300" : 0,
							"63000" : 1.3400000000000001,
							"63300" : 1.1500000000000001,
							"63600" : 1.1799999999999999,
							"63900" : 0.80000000000000004,
							"64200" : 0.20000000000000001,
							"64500" : 0.059999999999999998,
							"64800" : 0.17999999999999999,
							"65100" : 1.6300000000000001,
							"65400" : 1.49,
							"65700" : 0.35000000000000003,
							"6600" : 0,
							"66000" : 0.22,
							"66300" : 0.17000000000000001,
							"66600" : 0.13,
							"66900" : 0.070000000000000007,
							"67200" : 0,
							"67500" : 0,
							"67800" : 0,
							"68100" : 0,
							"68400" : 0,
							"68700" : 0,
							"6900" : 0,
							"69000" : 0,
							"69300" : 0,
							"69600" : 0,
							"69900" : 0,
							"70200" : 0,
							"70500" : 0,
							"70800" : 0,
							"71100" : 0,
							"71400" : 0,
							"71700" : 0,
							"7200" : 0,
							"72000" : 0,
							"72300" : 0,
							"72600" : 0,
							"72900" : 0,
							"73200" : 0,
							"73500" : 0,
							"73800" : 0,
							"74100" : 0,
							"74400" : 0,
							"74700" : 0,
							"7500" : 0,
							"75000" : 0,
							"75300" : 0,
							"75600" : 0,
							"75900" : 0,
							"76200" : 0,
							"76500" : 0,
							"76800" : 0,
							"77100" : 0,
							"77400" : 0,
							"77700" : 0,
							"7800" : 0,
							"78000" : 0,
							"78300" : 0,
							"78600" : 0,
							"78900" : 0,
							"79200" : 0,
							"79500" : 0,
							"79800" : 0,
							"80100" : 0,
							"80400" : 0,
							"80700" : 0,
							"8100" : 0,
							"81000" : 0,
							"81300" : 0,
							"81600" : 0,
							"81900" : 0,
							"82200" : 0,
							"82500" : 0,
							"82800" : 0,
							"83100" : 0,
							"83400" : 0,
							"83700" : 0,
							"8400" : 0,
							"84000" : 0,
							"84300" : 0,
							"84600" : 0,
							"84900" : 0,
							"85200" : 0,
							"85500" : 0,
							"85800" : 0,
							"86100" : 0,
							"8700" : 0,
							"900" : 0,
							"9000" : 0,
							"9300" : 0,
							"9600" : 0,
							"9900" : 0
						},
						"_comment" : "channelId=66050"
					},
					"Current_DC_String_2" : 
					{
						"Unit" : "A",
						"Values" : 
						{
							"0" : 0,
							"10200" : 0,
							"10500" : 0,
							"10800" : 0,
							"11100" : 0,
							"11400" : 0,
							"11700" : 0,
							"1200" : 0,
							"12000" : 0,
							"12300" : 0,
							"12600" : 0,
							"12900" : 0,
							"13200" : 0,
							"13500" : 0,
							"13800" : 0,
							"14100" : 0,
							"14400" : 0,
							"14700" : 0,
							"1500" : 0,
							"15000" : 0,
							"15300" : 0,
							"15600" : 0,
							"15900" : 0,
							"16200" : 0,
							"16500" : 0,
							"16800" : 0,
							"17100" : 0,
							"17400" : 0,
							"17700" : 0,
							"1800" : 0,
							"18000" : 0,
							"18300" : 0,
							"18600" : 0,
							"18900" : 0,
							"19200" : 0,
							"19500" : 0,
							"19800" : 0,
							"20100" : 0,
							"20400" : 0,
							"20700" : 0,
							"2100" : 0,
							"21000" : 0,
							"21300" : 0,
							"21600" : 0,
							"21900" : 0,
							"22200" : 0,
							"22500" : 0,
							"22800" : 0,
							"23100" : 0,
							"23400" : 0,
							"23700" : 0,
							"2400" : 0,
							"24000" : 0,
							"24300" : 0,
							"24600" : 0,
							"24900" : 0,
							"25200" : 0,
							"25500" : 0,
							"25800" : 0.029999999999999999,
							"26100" : 0.059999999999999998,
							"26400" : 0.089999999999999997,
							"26700" : 0.14999999999999999,
							"2700" : 0,
							"27000" : 0.17999999999999999,
							"27300" : 0.20000000000000001,
							"27600" : 0.22,
							"27900" : 0.20999999999999999,
							"28200" : 0.25,
							"28500" : 0.20999999999999999,
							"28800" : 0.31,
							"29100" : 0.40000000000000002,
							"29400" : 0.44,
							"29700" : 0.48999999999999999,
							"300" : 0,
							"3000" : 0,
							"30000" : 0.57000000000000006,
							"30300" : 0.66000000000000003,
							"30600" : 0.62,
							"30900" : 0.68000000000000005,
							"31200" : 0.71999999999999997,
							"31500" : 0.95000000000000007,
							"31800" : 1.0700000000000001,
							"32100" : 1.23,
							"32400" : 1.3300000000000001,
							"32700" : 1.21,
							"3300" : 0,
							"33000" : 1.1699999999999999,
							"33300" : 1.1400000000000001,
							"33600" : 1.0900000000000001,
							"33900" : 1.1899999999999999,
							"34200" : 1.23,
							"34500" : 1.4399999999999999,
							"34800" : 1.8400000000000001,
							"35100" : 1.8600000000000001,
							"35400" : 1.8300000000000001,
							"35700" : 1.73,
							"3600" : 0,
							"36000" : 1.73,
							"36300" : 1.9000000000000001,
							"36600" : 1.6500000000000001,
							"36900" : 0.81000000000000005,
							"37200" : 0.41000000000000003,
							"37500" : 0.71999999999999997,
							"37800" : 1.3400000000000001,
							"38100" : 1.1300000000000001,
							"38400" : 0.90000000000000002,
							"38700" : 0.67000000000000004,
							"3900" : 0,
							"39000" : 0.51000000000000001,
							"39300" : 0.42999999999999999,
							"39600" : 0.60999999999999999,
							"39900" : 0.79000000000000004,
							"40200" : 0.80000000000000004,
							"40500" : 0.98999999999999999,
							"40800" : 1.03,
							"41100" : 1.1599999999999999,
							"41400" : 1.1799999999999999,
							"41700" : 1.23,
							"4200" : 0,
							"42000" : 1.3300000000000001,
							"42300" : 1.1500000000000001,
							"42600" : 1.02,
							"42900" : 1.02,
							"43200" : 1.2,
							"43500" : 1.22,
							"43800" : 1.47,
							"44100" : 2.1800000000000002,
							"44400" : 2.3100000000000001,
							"44700" : 2.6899999999999999,
							"4500" : 0,
							"45000" : 3.0600000000000001,
							"45300" : 3.2400000000000002,
							"45600" : 3.29,
							"45900" : 3.27,
							"46200" : 3.0600000000000001,
							"46500" : 2.6000000000000001,
							"46800" : 2.3199999999999998,
							"47100" : 2.5300000000000002,
							"47400" : 1.8500000000000001,
							"47700" : 2.52,
							"4800" : 0,
							"48000" : 2.5699999999999998,
							"48300" : 2.3799999999999999,
							"48600" : 2.21,
							"48900" : 1.29,
							"49200" : 0.88,
							"49500" : 1.6300000000000001,
							"49800" : 2.1299999999999999,
							"50100" : 1.3800000000000001,
							"50400" : 1.7,
							"50700" : 2.48,
							"5100" : 0,
							"51000" : 2.8700000000000001,
							"51300" : 2.4100000000000001,
							"51600" : 2.71,
							"51900" : 1.75,
							"52200" : 1.1500000000000001,
							"52500" : 2.3700000000000001,
							"52800" : 2.1400000000000001,
							"53100" : 1.71,
							"53400" : 2.21,
							"53700" : 2.3100000000000001,
							"5400" : 0,
							"54000" : 2.46,
							"54300" : 3.3000000000000003,
							"54600" : 2.46,
							"54900" : 1.98,
							"55200" : 1.3600000000000001,
							"55500" : 1.23,
							"55800" : 1.6400000000000001,
							"56100" : 1.1300000000000001,
							"56400" : 1.5,
							"56700" : 1.0900000000000001,
							"5700" : 0,
							"57000" : 0.93000000000000005,
							"57300" : 1.1400000000000001,
							"57600" : 0.71999999999999997,
							"57900" : 0.42999999999999999,
							"58200" : 0.39000000000000001,
							"58500" : 0.56000000000000005,
							"58800" : 0.79000000000000004,
							"59100" : 0.72999999999999998,
							"59400" : 1.46,
							"59700" : 2.0100000000000002,
							"600" : 0,
							"6000" : 0,
							"60000" : 1.6600000000000001,
							"60300" : 1.5900000000000001,
							"60600" : 1.6799999999999999,
							"60900" : 1.6200000000000001,
							"61200" : 1.54,
							"61500" : 1.46,
							"61800" : 1.54,
							"62100" : 1.21,
							"62400" : 0.57999999999999996,
							"62700" : 0.51000000000000001,
							"6300" : 0,
							"63000" : 0.46000000000000002,
							"63300" : 0.35999999999999999,
							"63600" : 0.33000000000000002,
							"63900" : 0.20999999999999999,
							"64200" : 0.01,
							"64500" : 0,
							"64800" : 0.089999999999999997,
							"65100" : 0.5,
							"65400" : 0.39000000000000001,
							"65700" : 0.11,
							"6600" : 0,
							"66000" : 0.080000000000000002,
							"66300" : 0.050000000000000003,
							"66600" : 0.040000000000000001,
							"66900" : 0.02,
							"67200" : 0,
							"67500" : 0,
							"67800" : 0,
							"68100" : 0,
							"68400" : 0,
							"68700" : 0,
							"6900" : 0,
							"69000" : 0,
							"69300" : 0,
							"69600" : 0,
							"69900" : 0,
							"70200" : 0,
							"70500" : 0,
							"70800" : 0,
							"71100" : 0,
							"71400" : 0,
							"71700" : 0,
							"7200" : 0,
							"72000" : 0,
							"72300" : 0,
							"72600" : 0,
							"72900" : 0,
							"73200" : 0,
							"73500" : 0,
							"73800" : 0,
							"74100" : 0,
							"74400" : 0,
							"74700" : 0,
							"7500" : 0,
							"75000" : 0,
							"75300" : 0,
							"75600" : 0,
							"75900" : 0,
							"76200" : 0,
							"76500" : 0,
							"76800" : 0,
							"77100" : 0,
							"77400" : 0,
							"77700" : 0,
							"7800" : 0,
							"78000" : 0,
							"78300" : 0,
							"78600" : 0,
							"78900" : 0,
							"79200" : 0,
							"79500" : 0,
							"79800" : 0,
							"80100" : 0,
							"80400" : 0,
							"80700" : 0,
							"8100" : 0,
							"81000" : 0,
							"81300" : 0,
							"81600" : 0,
							"81900" : 0,
							"82200" : 0,
							"82500" : 0,
							"82800" : 0,
							"83100" : 0,
							"83400" : 0,
							"83700" : 0,
							"8400" : 0,
							"84000" : 0,
							"84300" : 0,
							"84600" : 0,
							"84900" : 0,
							"85200" : 0,
							"85500" : 0,
							"85800" : 0,
							"86100" : 0,
							"8700" : 0,
							"900" : 0,
							"9000" : 0,
							"9300" : 0,
							"9600" : 0,
							"9900" : 0
						},
						"_comment" : "channelId=131586"
					}
				},
				"DeviceType" : 115,
				"End" : "2021-03-13T23:59:59+01:00",
				"NodeType" : 97,
				"Start" : "2021-03-13T00:00:00+01:00"
			}
		}
	},
	"Head" : 
	{
		"RequestArguments" : 
		{
			"Channel" : 
			[
				"Current_DC_String_1",
				"Current_DC_String_2"
			],
			"EndDate" : "2021-03-13T23:59:59+01:00",
			"HumanReadable" : "True",
			"Scope" : "System",
			"SeriesType" : "Detail",
			"StartDate" : "2021-03-13T00:00:00+01:00"
		},
		"Status" : 
		{
			"Code" : 0,
			"ErrorDetail" : 
			{
				"Nodes" : []
			},
			"Reason" : "",
			"UserMessage" : ""
		},
		"Timestamp" : "2021-03-14T10:04:31+01:00"
	}
}

**Comment by pacco81** [comment]
Leider kommen nach Update auf 1.1.3 bei mir immer noch keine MPPT-Daten.

Beim Stöbern im Quellcode scheint es eine Funktion "GetArchiveData" zu geben. Im Log sehe ich keine Fehlermeldungen.
Was kann ich noch tun ? Da ich ein Norddach an einem eigenen String habe, würde ich gerne die Leistung dieses Strings beobachten im Vergleich zum Süddach. Leider geht das aktuell nur im FroniusSolarWeb.

**Comment by nkleber78** [comment]
Was hast du für ein Intervall für Archiv eingestellt?

**Comment by pacco81** [comment]
Hi !

Ich habe das 120s default gelassen.

P.S. Ich habe jetzt testweise die Objekte manuell angelegt. Jetzt werden dir Objekte vom Adapter mit Daten befüllt ! Also scheint es bei mir ein Problem bei der automatischen Anlage der Archiv-Objekte zu geben. Wenn ich logs o.Ä. zur Analyse beisteuern kann, bitte Bescheid sagen.

Auf jeden Fall Vielen Dank für die Adapterentwicklung! Bald kann ich meinen kostenpflichtigrn SolarEeb Account einsparen.

**Comment by nkleber78** [comment]
Das Problem habe ich bereits erkannt und gelöst in meinem Repository. Ist dann beim offiziellen Release gelöst

**Comment by pacco81** [comment]
Super. Dann werden die Objekte in Zukunft automatisch angelegt. Besten Dank !

**Comment by mcm1957** [comment]
Ist da noch was offen?
Ansonsten bitte label fixed setzen und comment "fxied with release 2.0.0 (oder was auch immer)

**Comment by nkleber78** [comment]
Implementiert in der Version 2.0.0
