### ISSUE TITLE
Power consumed from grid today/ power send to grid

### ISSUE THREAD

**Issue by m4ding** [iobroker-community-adapters/ioBroker.fronius#37]
Hi,

I‘m using v1.05 of the adapter. I could not find a value for the following two:
Power consumed from grid today (until now) 
Power send to grid today (until now)

Example shown on fronius website (left to grid, right from grid)

![EA12D941-4112-48A1-8EC3-241D6A1A0A28](https://user-images.githubusercontent.com/65028008/81506633-03b59d00-92f8-11ea-8f99-2f4b5bdfead2.jpeg)

Thanks!

**Comment by m4ding** [comment]
I have asked the Fronius Support. According to them, the value of power to/ from grid (P_Grid: http://froniusIP/solar_api/v1/GetPowerFlowRealtimeData.fcgi) must be saved each at midnight and upon next midnight like an electricity meter (which counts the electricity taken retrieved from the grid over the entire day) in order to subtract the two values.

**Comment by m4ding** [comment]
@schweigel wäre es möglich dass du dir das mal ansiehst? Das wäre eine super Erweiterung. Man könnte über iobroker dann sehen, wie viel Strom am Tag vom Netz bezogen wird.

**Comment by schweigel** [comment]
Hallo,

also in den PowerFlowRealtimeData konnte ich da nichts nützliches finden. Da wären zwar die aktuellen Werte wie P_Grid, aber die sind immer nur eine Momentaufnahme. Da diese während der Zeit schwanken können, wäre das nur sehr ungenau, wenn man das mit der Zeit zwischen den Messwerten multiplizieren würde.

Aber ich habe in den ArchivData die Werte EnergyReal_WAC_Minus_Absolute und EnergyReal_WAC_Plus_Absolute gefunden.
Diese geben bereits einen absoluten Verbrauch an. Wenn man nun jeweils den Tagesstartwert abzieht bekommt man den Tages Verbrauch.

An dieser Stelle müssen wir dann aber die genauen Grenzen für diesen Adapter abstecken.
Wir haben zwei Optionen:

1. Nur Werte auslesen
* die Daten EnergyReal_WAC_Minus_Absolute & EnergyReal_WAC_Plus_Absolute  werden wie die anderen Archivdaten zyklisch ausgelesen
* eine Verarbeitung der Zählerwerte zu Tages-, Wochen- und Monatswerten muss dann auf anderem Wege in ioBroker erfolgen

2. Werte auslesen und Statistiken berechnen
* die Daten EnergyReal_WAC_Minus_Absolute & EnergyReal_WAC_Plus_Absolute  werden wie die anderen Archivdaten zyklisch ausgelesen
* die ausgelesenen Daten werden statistisch verarbeitet und fallen als All-in-one-Lösung aus diesem Adapter raus

@ldittmar81 was meinst du dazu?

**Comment by schweigel** [comment]
Ich habe gesehen das die Werte *EnergyReal_WAC_Minus_Absolute* & *EnergyReal_WAC_Plus_Absolute* bereits als normale Messwerte enthalten sind. Daher ist die umständliche Abfrage über die Archivdaten nicht nötig.

Die Statistik der z.B. Tagesdaten kann dann via JavaScript erfolgen oder zum Beispiel über den Adapter [statistics](https://github.com/foxthefox/ioBroker.statistics).

**Comment by m4ding** [comment]
Hi,

ich habe es nun mit Blockly gelöst. Voraussetzung ist, dass das SmartMeter den kompletten Hausverbrsuch erfasst (an Position 0?). 

Zuerst die Datenpunkte als Zahl anlegen:

![10CFEB75-FEED-4AB4-A54F-B7A8B12D5CD7](https://user-images.githubusercontent.com/65028008/111027759-96c8d300-83f2-11eb-8597-c5680b2b1c61.jpeg)


`<xml xmlns="https://developers.google.com/blockly/xml">
  <variables>
    <variable id="-8PF#`5kx1eM55XS+2mq">NetzbezugAktuell</variable>
    <variable id="-`O;EzYvACeVPS+3KjnH">NetzbezugUmMitternacht</variable>
    <variable id="fy2pJDC?f|0HOfEOajCT">Netzbezug</variable>
    <variable id="M{G_i}a#(9?p=/5|b{?E">PVProduktion</variable>
    <variable id="bni6KKZ7T,g}raa~5ghd">EinspeisBezug</variable>
    <variable id="]Pj#~jR[#Bap^@K8j:*7">Hausverbrauch</variable>
    <variable id="J{1{_L@ZJTMUe#mdd8M3">AutarkieGerundet</variable>
  </variables>
  <block type="comment" id="jtKnUrHo!zjyyO{cA?0K" x="-2587" y="-3812">
    <field name="COMMENT">nachts Bezug setzen um Mitternacht</field>
    <next>
      <block type="schedule" id="=9h%5`.|%}F:(Qq(|LAr">
        <field name="SCHEDULE">{"time":{"exactTime":true,"start":"23:59"},"period":{"days":1}}</field>
        <statement name="STATEMENT">
          <block type="timeouts_wait" id=",}P;:%!iqmBDZyuwXwx{">
            <field name="DELAY">59</field>
            <field name="UNIT">sec</field>
            <next>
              <block type="variables_set" id="kKZf$t4vj*ta_+hnF-.H">
                <field name="VAR" id="-`O;EzYvACeVPS+3KjnH">NetzbezugUmMitternacht</field>
                <value name="VALUE">
                  <block type="get_value" id="^m]m#}2V|mO=1,Dd;O?E">
                    <field name="ATTR">val</field>
                    <field name="OID">fronius.0.meter.0.EnergyReal_WAC_Plus_Absolute</field>
                  </block>
                </value>
                <next>
                  <block type="update" id="BU#?h5G19IBr]Ufh#6Ps">
                    <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                    <field name="OID">javascript.0.scriptEnabled.EigeneDatenpunkte.Fronius.NetzbezugMitternacht</field>
                    <field name="WITH_DELAY">FALSE</field>
                    <value name="VALUE">
                      <block type="variables_get" id="c{v?vqDv=OJX,L+)RHDK">
                        <field name="VAR" id="-`O;EzYvACeVPS+3KjnH">NetzbezugUmMitternacht</field>
                      </block>
                    </value>
                    <next>
                      <block type="telegram" id="_`tL^`b+_*Er2|0-`?vs">
                        <field name="INSTANCE"></field>
                        <field name="LOG"></field>
                        <field name="SILENT">FALSE</field>
                        <field name="PARSEMODE">default</field>
                        <value name="MESSAGE">
                          <shadow type="text" id="{!@;7U`/K%kM^PaP[H:!">
                            <field name="TEXT">text</field>
                          </shadow>
                          <block type="text_join" id="O;kS=DDo,/ySbLP!A^@X">
                            <mutation items="2"></mutation>
                            <value name="ADD0">
                              <block type="text" id="mjQCtBluWIqxo|UIIZ,Y">
                                <field name="TEXT">Netzbezug um Mitternacht: </field>
                              </block>
                            </value>
                            <value name="ADD1">
                              <block type="variables_get" id="[Cv0~U6)W{:0.ITud=98">
                                <field name="VAR" id="-`O;EzYvACeVPS+3KjnH">NetzbezugUmMitternacht</field>
                              </block>
                            </value>
                          </block>
                        </value>
                      </block>
                    </next>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </statement>
      </block>
    </next>
  </block>
  <block type="comment" id="YIDYLoIs,)K.g,In,eLb" x="-1887" y="-3662">
    <field name="COMMENT">Aktuellen Verbrauch berechnen</field>
    <next>
      <block type="schedule" id="WhCB-0Pp%Lr=lGtD|vI]">
        <field name="SCHEDULE">* * * * *</field>
        <statement name="STATEMENT">
          <block type="variables_set" id="P~6)bE(je?q|ZaX8+c7{">
            <field name="VAR" id="-8PF#`5kx1eM55XS+2mq">NetzbezugAktuell</field>
            <value name="VALUE">
              <block type="get_value" id="jtaAD!=s1W5s[$(;QXBM">
                <field name="ATTR">val</field>
                <field name="OID">fronius.0.meter.0.EnergyReal_WAC_Plus_Absolute</field>
              </block>
            </value>
            <next>
              <block type="variables_set" id="](;)}1:7`x-FALxC}g9f">
                <field name="VAR" id="-`O;EzYvACeVPS+3KjnH">NetzbezugUmMitternacht</field>
                <value name="VALUE">
                  <block type="get_value" id="mQ0m=xrrX[`WyII[{C;)">
                    <field name="ATTR">val</field>
                    <field name="OID">javascript.0.scriptEnabled.EigeneDatenpunkte.Fronius.NetzbezugMitternacht</field>
                  </block>
                </value>
                <next>
                  <block type="variables_set" id="kbhdFj]dC4c+G~iTsRhx">
                    <field name="VAR" id="fy2pJDC?f|0HOfEOajCT">Netzbezug</field>
                    <value name="VALUE">
                      <block type="math_arithmetic" id="{KR~Dk]ro7H#)MaTa9K}">
                        <field name="OP">MINUS</field>
                        <value name="A">
                          <shadow type="math_number">
                            <field name="NUM">1</field>
                          </shadow>
                          <block type="variables_get" id="crO0FQ)$Z?Sn2)?`#Wwl">
                            <field name="VAR" id="-8PF#`5kx1eM55XS+2mq">NetzbezugAktuell</field>
                          </block>
                        </value>
                        <value name="B">
                          <shadow type="math_number" id="0vJVCXFr3DZ4(nR4iG_2">
                            <field name="NUM">1</field>
                          </shadow>
                          <block type="variables_get" id="K/mgIhFYBQN8j@UkJE%`">
                            <field name="VAR" id="-`O;EzYvACeVPS+3KjnH">NetzbezugUmMitternacht</field>
                          </block>
                        </value>
                      </block>
                    </value>
                    <next>
                      <block type="update" id="}cr7@V4Qh:$u`nwE.YRt">
                        <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                        <field name="OID">javascript.0.scriptEnabled.EigeneDatenpunkte.Fronius.NetzbezugJeTag</field>
                        <field name="WITH_DELAY">FALSE</field>
                        <value name="VALUE">
                          <block type="variables_get" id="U;UVKeBBq_qW(Bp`^Rj|">
                            <field name="VAR" id="fy2pJDC?f|0HOfEOajCT">Netzbezug</field>
                          </block>
                        </value>
                      </block>
                    </next>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </statement>
      </block>
    </next>
  </block>
  <block type="comment" id="LN:B@73Pjtb3ny,/%lFU" x="-2462" y="-1887">
    <field name="COMMENT">Hausverbrauch, Einspeisung und Netzbezug berechnen</field>
    <next>
      <block type="schedule" id="UVWP0[+Oj79e/`5%G@sH">
        <field name="SCHEDULE">*/5 * * * * *</field>
        <statement name="STATEMENT">
          <block type="comment" id="Ls3L;#+).KG7{v#(e9Dh">
            <field name="COMMENT">Hausverbrauch wenn Einspeisung (Wert negativ), dann Wert in temp. Variable schreiben, negativer Bezug positiv, voneinander abziehen und in Wert schreiben</field>
            <next>
              <block type="controls_if" id="7fKvuBL!/MAw]g5C(Ia[">
                <value name="IF0">
                  <block type="logic_compare" id="mKA9*/3^f8(smgLu_G=|">
                    <field name="OP">LTE</field>
                    <value name="A">
                      <block type="get_value" id="p?5g9+Mo58VH4/oAE=AB">
                        <field name="ATTR">val</field>
                        <field name="OID">fronius.0.powerflow.P_Grid</field>
                      </block>
                    </value>
                    <value name="B">
                      <block type="math_number" id="ZM(S!VVV`x/d(!M_A6Tv">
                        <field name="NUM">0</field>
                      </block>
                    </value>
                  </block>
                </value>
                <statement name="DO0">
                  <block type="variables_set" id="R?*[oEg)zc!)u=51*bw6">
                    <field name="VAR" id="M{G_i}a#(9?p=/5|b{?E">PVProduktion</field>
                    <value name="VALUE">
                      <block type="get_value" id="]!8Y+)*R+.o,}Ty47^z%">
                        <field name="ATTR">val</field>
                        <field name="OID">fronius.0.powerflow.P_PV</field>
                      </block>
                    </value>
                    <next>
                      <block type="variables_set" id="l`Z*i1TOZO*F_fBBWQ}7">
                        <field name="VAR" id="bni6KKZ7T,g}raa~5ghd">EinspeisBezug</field>
                        <value name="VALUE">
                          <block type="get_value" id="Ieue.HEf`,W5sTQSS,`u">
                            <field name="ATTR">val</field>
                            <field name="OID">fronius.0.powerflow.P_Grid</field>
                          </block>
                        </value>
                        <next>
                          <block type="variables_set" id="ClbX8IZq-c)a3?,BgoMu">
                            <field name="VAR" id="bni6KKZ7T,g}raa~5ghd">EinspeisBezug</field>
                            <value name="VALUE">
                              <block type="math_arithmetic" id="1NY@cMm$2fEr0.5a0@Vo">
                                <field name="OP">MULTIPLY</field>
                                <value name="A">
                                  <shadow type="math_number" id="jX0u2z_)uqS:G)^dy*zx">
                                    <field name="NUM">1</field>
                                  </shadow>
                                  <block type="variables_get" id="m]7`Pf.s^OXu($3;v|O8">
                                    <field name="VAR" id="bni6KKZ7T,g}raa~5ghd">EinspeisBezug</field>
                                  </block>
                                </value>
                                <value name="B">
                                  <shadow type="math_number" id="TOzhLP[[FGG8u/.TG79~">
                                    <field name="NUM">-1</field>
                                  </shadow>
                                </value>
                              </block>
                            </value>
                            <next>
                              <block type="variables_set" id="S=[M1M@NJ@i{qRGMyjrF">
                                <field name="VAR" id="]Pj#~jR[#Bap^@K8j:*7">Hausverbrauch</field>
                                <value name="VALUE">
                                  <block type="math_arithmetic" id="8;*_|}KK5S0V]k*%#vy=">
                                    <field name="OP">MINUS</field>
                                    <value name="A">
                                      <shadow type="math_number" id="7uPW7ls`}CUi5:,)xJU?">
                                        <field name="NUM">1</field>
                                      </shadow>
                                      <block type="variables_get" id="5A1{zOMJI@Z=7$]?T4-2">
                                        <field name="VAR" id="M{G_i}a#(9?p=/5|b{?E">PVProduktion</field>
                                      </block>
                                    </value>
                                    <value name="B">
                                      <shadow type="math_number" id="[|s2X(n~W$big(#qQCTq">
                                        <field name="NUM">1</field>
                                      </shadow>
                                      <block type="variables_get" id="I^/{#^kA+8SI{##*ua62">
                                        <field name="VAR" id="bni6KKZ7T,g}raa~5ghd">EinspeisBezug</field>
                                      </block>
                                    </value>
                                  </block>
                                </value>
                                <next>
                                  <block type="update" id="Plf4d3#t4{K!MX]%|[.g">
                                    <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                                    <field name="OID">javascript.0.scriptEnabled.EigeneDatenpunkte.Fronius.Hausverbrauch</field>
                                    <field name="WITH_DELAY">FALSE</field>
                                    <value name="VALUE">
                                      <block type="math_round" id="[9y1YZNod%|yMoV]wWK4">
                                        <field name="OP">ROUNDDOWN</field>
                                        <value name="NUM">
                                          <shadow type="math_number" id="nRFr`3PV3njG(y6rpcVI">
                                            <field name="NUM">3.1</field>
                                          </shadow>
                                          <block type="math_rndfixed" id="Z?UUPMDtuRo]he:FAat]">
                                            <field name="n">1</field>
                                            <value name="x">
                                              <shadow type="math_number">
                                                <field name="NUM">3.1234</field>
                                              </shadow>
                                              <block type="variables_get" id=";P}Z;;0QviO(j+7;+Eek">
                                                <field name="VAR" id="]Pj#~jR[#Bap^@K8j:*7">Hausverbrauch</field>
                                              </block>
                                            </value>
                                          </block>
                                        </value>
                                      </block>
                                    </value>
                                    <next>
                                      <block type="update" id="`1W/=Q6$+5j#$ycfv6==" disabled="true">
                                        <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                                        <field name="OID">javascript.0.scriptEnabled.EigeneDatenpunkte.Fronius.Hausverbrauch</field>
                                        <field name="WITH_DELAY">FALSE</field>
                                        <value name="VALUE">
                                          <block type="variables_get" id=":w/.(wou(VrHoR2_{;n^">
                                            <field name="VAR" id="]Pj#~jR[#Bap^@K8j:*7">Hausverbrauch</field>
                                          </block>
                                        </value>
                                      </block>
                                    </next>
                                  </block>
                                </next>
                              </block>
                            </next>
                          </block>
                        </next>
                      </block>
                    </next>
                  </block>
                </statement>
                <next>
                  <block type="comment" id="uDDB^.*6E5#u($[gsSr2">
                    <field name="COMMENT">Hausverbrauch wenn keine Einspeisung, Werte in temp. schreiben und voneinander abziehen, in Datenpunkt schreiben</field>
                    <next>
                      <block type="controls_if" id="dMN++NOHHd7E(Z9c`;sP">
                        <value name="IF0">
                          <block type="logic_compare" id="|%D7.GyZras{qaV7eh:T">
                            <field name="OP">GTE</field>
                            <value name="A">
                              <block type="get_value" id="6LE5-)W,wK3Nj12i/:r|">
                                <field name="ATTR">val</field>
                                <field name="OID">fronius.0.powerflow.P_Grid</field>
                              </block>
                            </value>
                            <value name="B">
                              <block type="math_number" id="sT,cNevQK^_r$j*5A4v*">
                                <field name="NUM">0</field>
                              </block>
                            </value>
                          </block>
                        </value>
                        <statement name="DO0">
                          <block type="variables_set" id="ot,2_/%+Dl[KtW7l`fhM">
                            <field name="VAR" id="M{G_i}a#(9?p=/5|b{?E">PVProduktion</field>
                            <value name="VALUE">
                              <block type="get_value" id="s6*xljZ/=u~#tF|PJ,}S">
                                <field name="ATTR">val</field>
                                <field name="OID">fronius.0.powerflow.P_PV</field>
                              </block>
                            </value>
                            <next>
                              <block type="variables_set" id="9SZC:?Sdua:T7i]WUjaG">
                                <field name="VAR" id="bni6KKZ7T,g}raa~5ghd">EinspeisBezug</field>
                                <value name="VALUE">
                                  <block type="get_value" id="SqM`HXh3x|.eR6yL1idK">
                                    <field name="ATTR">val</field>
                                    <field name="OID">fronius.0.powerflow.P_Grid</field>
                                  </block>
                                </value>
                                <next>
                                  <block type="variables_set" id="_E=1;KobG3KMnrq7GA/|">
                                    <field name="VAR" id="]Pj#~jR[#Bap^@K8j:*7">Hausverbrauch</field>
                                    <value name="VALUE">
                                      <block type="math_arithmetic" id="A=xO@^}[p_Zx!V0Z]{i^">
                                        <field name="OP">ADD</field>
                                        <value name="A">
                                          <shadow type="math_number">
                                            <field name="NUM">1</field>
                                          </shadow>
                                          <block type="variables_get" id="L=I~r:F|n2V+e}Z-v,`^">
                                            <field name="VAR" id="M{G_i}a#(9?p=/5|b{?E">PVProduktion</field>
                                          </block>
                                        </value>
                                        <value name="B">
                                          <shadow type="math_number">
                                            <field name="NUM">1</field>
                                          </shadow>
                                          <block type="variables_get" id="*z{uW-#wqtial|ouYO$K">
                                            <field name="VAR" id="bni6KKZ7T,g}raa~5ghd">EinspeisBezug</field>
                                          </block>
                                        </value>
                                      </block>
                                    </value>
                                    <next>
                                      <block type="update" id="SW0[=Bp7wZFm7yhFhk1i">
                                        <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                                        <field name="OID">javascript.0.scriptEnabled.EigeneDatenpunkte.Fronius.Hausverbrauch</field>
                                        <field name="WITH_DELAY">FALSE</field>
                                        <value name="VALUE">
                                          <block type="math_rndfixed" id="ee6]ngc-nc,OKd64STrm">
                                            <field name="n">1</field>
                                            <value name="x">
                                              <shadow type="math_number" id="/TWc{A!Td2]8uE?A]z[0">
                                                <field name="NUM">3.1234</field>
                                              </shadow>
                                              <block type="math_round" id="HQn~}TK+yV6+BWmC6/d~">
                                                <field name="OP">ROUNDDOWN</field>
                                                <value name="NUM">
                                                  <shadow type="math_number" id="Z1uplfHIsSXxf;ny`%C|">
                                                    <field name="NUM">3.1</field>
                                                  </shadow>
                                                  <block type="variables_get" id="T_2Wj^I=4eQZ!wvKXV.Y">
                                                    <field name="VAR" id="]Pj#~jR[#Bap^@K8j:*7">Hausverbrauch</field>
                                                  </block>
                                                </value>
                                              </block>
                                            </value>
                                          </block>
                                        </value>
                                        <next>
                                          <block type="update" id="]Xg/GFVWRVMKrW%G|^LP" disabled="true">
                                            <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                                            <field name="OID">javascript.0.scriptEnabled.EigeneDatenpunkte.Fronius.Hausverbrauch</field>
                                            <field name="WITH_DELAY">FALSE</field>
                                            <value name="VALUE">
                                              <block type="variables_get" id="k=h0/kJj=6[]Iw-=OZ69">
                                                <field name="VAR" id="]Pj#~jR[#Bap^@K8j:*7">Hausverbrauch</field>
                                              </block>
                                            </value>
                                          </block>
                                        </next>
                                      </block>
                                    </next>
                                  </block>
                                </next>
                              </block>
                            </next>
                          </block>
                        </statement>
                        <next>
                          <block type="comment" id="W_JH}_89F`vIXv:{r?D}">
                            <field name="COMMENT">Hausverbrauch: Einspeisung rausschreiben (*-1)</field>
                            <next>
                              <block type="controls_if" id="rtR#?%jfik.|i!M#70TL">
                                <value name="IF0">
                                  <block type="logic_compare" id=".)oi`/=|H$v/=_AZL2aC">
                                    <field name="OP">LT</field>
                                    <value name="A">
                                      <block type="get_value" id="dZ[F=Ug`?;F3/Mg0$y/s">
                                        <field name="ATTR">val</field>
                                        <field name="OID">fronius.0.powerflow.P_Grid</field>
                                      </block>
                                    </value>
                                    <value name="B">
                                      <block type="math_number" id=")L=[BiIEqBSDN8Atj-;4">
                                        <field name="NUM">0</field>
                                      </block>
                                    </value>
                                  </block>
                                </value>
                                <statement name="DO0">
                                  <block type="variables_set" id="A$0[E%mvQ#xrHAf,@-AA">
                                    <field name="VAR" id="bni6KKZ7T,g}raa~5ghd">EinspeisBezug</field>
                                    <value name="VALUE">
                                      <block type="get_value" id="KSOgrRx4Vh/lzS]06Dj^">
                                        <field name="ATTR">val</field>
                                        <field name="OID">fronius.0.powerflow.P_Grid</field>
                                      </block>
                                    </value>
                                    <next>
                                      <block type="variables_set" id="U[)/eI$mn361~e)[}/0Q">
                                        <field name="VAR" id="bni6KKZ7T,g}raa~5ghd">EinspeisBezug</field>
                                        <value name="VALUE">
                                          <block type="math_arithmetic" id="4nAbG1Cm4Dqc@,CA3}k_">
                                            <field name="OP">MULTIPLY</field>
                                            <value name="A">
                                              <shadow type="math_number">
                                                <field name="NUM">1</field>
                                              </shadow>
                                              <block type="variables_get" id="^dT38~zq;V6_7^m+.j/g">
                                                <field name="VAR" id="bni6KKZ7T,g}raa~5ghd">EinspeisBezug</field>
                                              </block>
                                            </value>
                                            <value name="B">
                                              <shadow type="math_number" id=",?EN|FCD5x9Ppm)3:gLz">
                                                <field name="NUM">-1</field>
                                              </shadow>
                                            </value>
                                          </block>
                                        </value>
                                        <next>
                                          <block type="update" id="_zyzEvkm,m+ur7Gx`w+I">
                                            <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                                            <field name="OID">javascript.0.scriptEnabled.EigeneDatenpunkte.Fronius.Einspeisung</field>
                                            <field name="WITH_DELAY">FALSE</field>
                                            <value name="VALUE">
                                              <block type="math_round" id="=52YFd=55gndS|$84Db]">
                                                <field name="OP">ROUNDDOWN</field>
                                                <value name="NUM">
                                                  <shadow type="math_number" id="OtD`H/x6X.hP]1IB^5C8">
                                                    <field name="NUM">0</field>
                                                  </shadow>
                                                  <block type="math_rndfixed" id="=l6p}rBLb9L4ixfMVWS]">
                                                    <field name="n">1</field>
                                                    <value name="x">
                                                      <shadow type="math_number" id="nN(UA~UQU2ag1u{{%ORI">
                                                        <field name="NUM">3.1234</field>
                                                      </shadow>
                                                      <block type="variables_get" id="9LSwjfuIRXfqow$v1CPy">
                                                        <field name="VAR" id="bni6KKZ7T,g}raa~5ghd">EinspeisBezug</field>
                                                      </block>
                                                    </value>
                                                  </block>
                                                </value>
                                              </block>
                                            </value>
                                          </block>
                                        </next>
                                      </block>
                                    </next>
                                  </block>
                                </statement>
                                <next>
                                  <block type="comment" id="{uoQyz~EWI52ixHu/Va(">
                                    <field name="COMMENT">Netzbezug Grid größer 0</field>
                                    <next>
                                      <block type="controls_if" id="@p`iAI8na~G(WPybq?93">
                                        <value name="IF0">
                                          <block type="logic_compare" id="RwC1dio5*X(ZXMZNn%4D">
                                            <field name="OP">GT</field>
                                            <value name="A">
                                              <block type="get_value" id="bCRt_-~1!}xxzP5~?pK9">
                                                <field name="ATTR">val</field>
                                                <field name="OID">fronius.0.powerflow.P_Grid</field>
                                              </block>
                                            </value>
                                            <value name="B">
                                              <block type="math_number" id="5:uTQI!8%BceHlc8urKL">
                                                <field name="NUM">0</field>
                                              </block>
                                            </value>
                                          </block>
                                        </value>
                                        <statement name="DO0">
                                          <block type="variables_set" id="L$5TvCOoh.fUIEK;d3U4">
                                            <field name="VAR" id="fy2pJDC?f|0HOfEOajCT">Netzbezug</field>
                                            <value name="VALUE">
                                              <block type="get_value" id="a7kHb*clUA-^F$*jx]n7">
                                                <field name="ATTR">val</field>
                                                <field name="OID">fronius.0.powerflow.P_Grid</field>
                                              </block>
                                            </value>
                                            <next>
                                              <block type="update" id="AkfhAdo5uxStb-m2}fCm">
                                                <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                                                <field name="OID">javascript.0.scriptEnabled.EigeneDatenpunkte.Fronius.Netzbezug</field>
                                                <field name="WITH_DELAY">FALSE</field>
                                                <value name="VALUE">
                                                  <block type="variables_get" id="LCFSH#@FqT9g21wkKUw6">
                                                    <field name="VAR" id="fy2pJDC?f|0HOfEOajCT">Netzbezug</field>
                                                  </block>
                                                </value>
                                              </block>
                                            </next>
                                          </block>
                                        </statement>
                                        <next>
                                          <block type="comment" id="ZB|C3^f?/-*,5g2[iLL2">
                                            <field name="COMMENT">Falls keine Einspeisung (grösser 0) dann Einspeisung 0 setzen</field>
                                            <next>
                                              <block type="controls_if" id="uX$HAz]fpPbtBFb8jj6B">
                                                <value name="IF0">
                                                  <block type="logic_compare" id="bBUE0Jv7kzY(7}54;L?D">
                                                    <field name="OP">GTE</field>
                                                    <value name="A">
                                                      <block type="get_value" id="m%HT%}X*1e]%4$V3Hd1}">
                                                        <field name="ATTR">val</field>
                                                        <field name="OID">fronius.0.powerflow.P_Grid</field>
                                                      </block>
                                                    </value>
                                                    <value name="B">
                                                      <block type="math_number" id="4atB7*5odGGRju3E{qWo">
                                                        <field name="NUM">0</field>
                                                      </block>
                                                    </value>
                                                  </block>
                                                </value>
                                                <statement name="DO0">
                                                  <block type="update" id=":23U5?/~i-D`?EN+kvU#">
                                                    <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                                                    <field name="OID">javascript.0.scriptEnabled.EigeneDatenpunkte.Fronius.Einspeisung</field>
                                                    <field name="WITH_DELAY">FALSE</field>
                                                    <value name="VALUE">
                                                      <block type="math_number" id="9K(nUA[0PP.lcF^A4EOA">
                                                        <field name="NUM">0</field>
                                                      </block>
                                                    </value>
                                                  </block>
                                                </statement>
                                                <next>
                                                  <block type="comment" id="Z[sJ_^)OlVb[|1X1T-n{">
                                                    <field name="COMMENT">Falls kein Netzbezug (grösser 0) dann Netzbezug 0 setzen</field>
                                                    <next>
                                                      <block type="controls_if" id="5HG.APDNb-XSpQ0S}+So">
                                                        <value name="IF0">
                                                          <block type="logic_compare" id="@,ScGkL*wSY7q-3Bq548">
                                                            <field name="OP">LTE</field>
                                                            <value name="A">
                                                              <block type="get_value" id="2ZNO*R;U/aJ+Rl8hU?Pq">
                                                                <field name="ATTR">val</field>
                                                                <field name="OID">fronius.0.powerflow.P_Grid</field>
                                                              </block>
                                                            </value>
                                                            <value name="B">
                                                              <block type="math_number" id="Wjb={j@24^Tm_cqA{|KY">
                                                                <field name="NUM">0</field>
                                                              </block>
                                                            </value>
                                                          </block>
                                                        </value>
                                                        <statement name="DO0">
                                                          <block type="update" id="wLTvM56SV*2|2(vewOQD">
                                                            <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                                                            <field name="OID">javascript.0.scriptEnabled.EigeneDatenpunkte.Fronius.Netzbezug</field>
                                                            <field name="WITH_DELAY">FALSE</field>
                                                            <value name="VALUE">
                                                              <block type="math_number" id="BEhN5-ye7*s$vEtCJ%oU">
                                                                <field name="NUM">0</field>
                                                              </block>
                                                            </value>
                                                          </block>
                                                        </statement>
                                                        <next>
                                                          <block type="variables_set" id="ausIU[js6S(p5O-lh}EX">
                                                            <field name="VAR" id="J{1{_L@ZJTMUe#mdd8M3">AutarkieGerundet</field>
                                                            <value name="VALUE">
                                                              <block type="get_value" id="U*TB#ZDPrS%rV(9$Q[aS">
                                                                <field name="ATTR">val</field>
                                                                <field name="OID">fronius.0.powerflow.rel_Autonomy</field>
                                                              </block>
                                                            </value>
                                                            <next>
                                                              <block type="update" id="q|8XmBQ.g#h(s]chd?@@">
                                                                <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                                                                <field name="OID">javascript.0.scriptEnabled.EigeneDatenpunkte.Fronius.AutarkieGerundet</field>
                                                                <field name="WITH_DELAY">FALSE</field>
                                                                <value name="VALUE">
                                                                  <block type="math_round" id="he/_-N(^#Pl@czDL~r?.">
                                                                    <field name="OP">ROUNDDOWN</field>
                                                                    <value name="NUM">
                                                                      <shadow type="math_number" id="*yR-f[76V~-55|IjIj,v">
                                                                        <field name="NUM">3.1</field>
                                                                      </shadow>
                                                                      <block type="math_rndfixed" id="ptbVM2_GIKq?f*[ihP;Q">
                                                                        <field name="n">1</field>
                                                                        <value name="x">
                                                                          <shadow type="math_number">
                                                                            <field name="NUM">3.1234</field>
                                                                          </shadow>
                                                                          <block type="variables_get" id="Bddzt^fI}WH.@krPwfeK">
                                                                            <field name="VAR" id="J{1{_L@ZJTMUe#mdd8M3">AutarkieGerundet</field>
                                                                          </block>
                                                                        </value>
                                                                      </block>
                                                                    </value>
                                                                  </block>
                                                                </value>
                                                              </block>
                                                            </next>
                                                          </block>
                                                        </next>
                                                      </block>
                                                    </next>
                                                  </block>
                                                </next>
                                              </block>
                                            </next>
                                          </block>
                                        </next>
                                      </block>
                                    </next>
                                  </block>
                                </next>
                              </block>
                            </next>
                          </block>
                        </next>
                      </block>
                    </next>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </statement>
      </block>
    </next>
  </block>
</xml> `

NetzbezugJeTag liefert den Wert in Wh und kann dann über vis/ Grafana etc. angezeigt werden. 

Bei mir läuft es gut.

**Comment by m4ding** [comment]
sorry die Fode Formatierung ist nicht wirklich gut.

**Comment by mcm1957** [comment]
Der Adapter soll(te) jene Werte auslesen die das Device bietet,
Für statistische Abfragen, Archivierungen etc. gibts eigen Adapter.

Ich schließe daher hier mal.
