### ISSUE TITLE
iobroker.siemenssimaticS7

### ISSUE THREAD

**Issue by nyessthorin** [iobroker-community-adapters/ioBroker.fronius#382]
Hallo,
ich weiß nicht ob das hier an der richtigen Stelle ist, aber ich habe ein Problem mit der Siemens Simatic S7 Instanz im IOBroker, welche ich für eine Steuerung  (Siemens Logo) benötige. Wenn ich bei den Einstellungen die IP Adresse eingebe und alles speichere, kommt bei "Verbindung mit Host" und "Lebenszeichen" ein grüner Haken, bei "Verbunden mit Gerät oder Dienst" allerdings ein rotes Kreuz und ich kann auch nichts von der Logo abfragen.

Was mache ich falsch? Ich bin absoluter Anfänger auf diesem Gebiet und freue mich über jeden Tiipp!

**Comment by mcm1957** [comment]
Wie richtig vermutest bist du hier falsch. Diese Repo beinhaltet den Adapter ioBroker.fronius.

Für allgemeine Fragen verwende bitte das Forum forum.iobroker.net. 

Probleme mit einem Adapter bitte im jeweiligen Adapter Repository melden.

Und on allen Fällen bitte die beteiligten Versionen angeben

Adapter
Admin
Js-controller
Node
O/S
