### ISSUE TITLE
Adapter nicht verbunden mit Fronius

### ISSUE THREAD

**Issue by BenjaminH1988** [iobroker-community-adapters/ioBroker.fronius#39]
Ich habe das Problem, dass der Adapter nach dem Umzug auf einen Intel NUC mit Proxmox sich nicht verbinden lässt.

Ich habe die IP-Adresse neu eingegeben aber es kommt immer
Verbunden mit Host: Wahr
Lebenszeichen: Wahr
Verbunden mit Fronius: falsch

**Comment by Tommmek** [comment]
Hallo ich habe genau das gleiche Problem

**Comment by Triple-M77** [comment]
Ich habe heute den Fronius Adapter zum ersten Mal installiert (V1.1.6) und bekomme auch keine Verbindung zu meinem Gen24. Wie oben schon geschrieben sind die ersten beiden Punkte grün aber der letzte rot und der Adapter steht somit auf gelb. Was kann man machen?

**Comment by HemanMaster** [comment]
Hallo ich hab das selbe Problem, hat jemand von euch eine Lösung? Ich gebe doch im Adapter nur die IP:Adresse ein oder? Brauch ich noch einen Port? Danke

**Comment by Mesok77** [comment]
Bei mir lag das Problem darin, dass die Solar_Api im Wechselrichter deaktiviert war.
Diese kann man im WR unter Kommunikation-->Solar API aktivieren.

**Comment by mcm1957** [comment]
Sollte das Problem mit der aktuellen Release noch immer auftreten, bitte ein neues Issue öffnen.
