### ISSUE TITLE
Adapter not starting after upgrading to 2.1.0

### ISSUE THREAD

**Issue by mi3dke** [iobroker-community-adapters/ioBroker.fronius#460]
Hi,
I just installed the upgrade to 2.1.0 from 2.0.2. Everything was working before.
This was the only installation today. All adapters, node etc. have been updated earlier already on a regular base 
After the installation the adapter is not connecting. 
![image](https://github.com/iobroker-community-adapters/ioBroker.fronius/assets/85009218/e079ac12-c4e3-438c-8919-ded18bd8cf22)
In the log there is an error-message.
![image](https://github.com/iobroker-community-adapters/ioBroker.fronius/assets/85009218/5c273f33-55b0-483a-ac48-c7429d956e1e)
But I have admin 6.13.16 installed and running. (since longer already and rebooted etc. ) 
![image](https://github.com/iobroker-community-adapters/ioBroker.fronius/assets/85009218/26089e18-7f10-40f8-930d-acbab5a985d8)
Also the frameworks are updated.
![image](https://github.com/iobroker-community-adapters/ioBroker.fronius/assets/85009218/edab068b-65ff-40c6-af29-c91a8816fddf)
I tried to downgrad to 2.0.2 and 2.0.1 but no success. Not starting and also showing the adapter size with 0MB. 
![image](https://github.com/iobroker-community-adapters/ioBroker.fronius/assets/85009218/82674c8d-d80e-4ae8-bcb3-f66d013c2df4)
As the adapter is sending data to influx I can see it stopped exactly when I did the update so it is pretty obvious, the upgrade of the adapter lead to the problem. And the root cause seems to be a faulty detection of a version dependency with admin.
This is also the reason I did not try uninstalling and reinstalling the whole adapter. I am afraid after this I will end up with a new measurement series in influx.

Any idea?

Thanks
Michael

**Comment by mi3dke** [comment]
I tried different things but finally it got really messy so that the installation of the adapter worked but did not show up in instances anymore ... I decided to restore a regular backup that was luckily only an hour old and that worked, ie. after the restore was finished I was able to upgrade to version 2.1.0 without a problem.
Not sure what went wrong with the upgrade attempt I did earlier.

**Comment by mcm1957** [comment]
Adapter has not been started as admin dependencies did not match. This check is not perfomed by adapter but by js-controller which logs the message too. So this is never a issue of the adapter.

Why js-controller reported admin to be older than installed cannot be investigated as it seems to work now. And this would also be a issue of admin / js-controller. Maybe an iob upload goit lost somewhere.

**Comment by mi3dke** [comment]
Thanks for the explanation, Martin.
This could help next time ...

**Comment by mcm1957** [comment]
One addition:
If using a multihost system the admin dependency must be fulfilled at ALL hosts. 

In this case the error message is not optimal.
See https://github.com/ioBroker/ioBroker.js-controller/issues/2762
