### ISSUE TITLE
lookup table for status code (and other) missing

### ISSUE THREAD

**Issue by lu-as** [iobroker-community-adapters/ioBroker.fronius#498]
**Describe the bug**  
PV inverter says "status code: 7" in IOBroker, which probably means "everything is fine". I'd like to see a table that translates these values in "OK", "warning", "error" etc.
Same question for "Show" and "ErrorCode"

**To Reproduce**  
In IOBroker, go to Objects>fronius>0>inverter>1>StatusCode. A value like "7" is shown, but without description.

**Expected behavior**  
I'd like to see a table (probably here in documentation) that points out which state means what.

**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: 2.1.1
 - JS-Controller version: 6.0.11
 - Node version: 18.17.1
 - Operating system: RaspBian 11

**Additional context**

**Comment by mcm1957** [comment]
Do you have a table of values and corresponding description?
Or a link to such a docu?

**Comment by lu-as** [comment]
No, I didn't find this.
What came to my mind is that 7 is 111 in binary, so this could be a 3-bit-code. In [Fronius ModBus documentation](https://www.fronius.com/~/downloads/Solar%20Energy/Operating%20Instructions/gen24-modbus-api-external-docs.zip) I find something that might support this idea: 

`"Customer" event severity level bitfield  bit 0 -> Error  bit 1 -> Warning  bit 2 -> InfoThis bitfield is composed as a superposition for the severity-levels of all currently active events on view level "Customer".If a bit is set it means that currently there is at least one active event with this severity level. Multiple bits can be set at once indicating several active events with different severity-levels.`

This might go together with errorcode in Fronius IOBroker adapter, which is 0 in my case.

Oh, and in https://manuals.fronius.com/html/4204102649/de.html#0_m_0000014565, I find a table that mentions "operating codes" from 1 to 8, where 7 would point out an error. But the inverter's web interface just says "status: running".

**Comment by nkleber78** [comment]
@lu-as 
These codes are already translated to messages. The InverterErrorState translates the ErrorCode and the InverterState translates the StatusCode
![image](https://github.com/user-attachments/assets/76f42bfa-5a9b-40da-a728-f378653419ee)

**Comment by lu-as** [comment]
Oh great, thank you for providing the complete overview!
Up to now, my Grafana dashboard shows the status of SMA inverters, mapping SMA's status codes in intuitively comprehensible colours. Your table helps me to integrate Fronius states in the same scheme.
