### ISSUE TITLE
Batterie schaltet sich beim Auslesen der Daten aus

### ISSUE THREAD

**Issue by ldittmar81** [iobroker-community-adapters/ioBroker.fronius#5]
Hallo. Ich hab das auf Deinen Rat hin ausprobiert, aber leider gibt der Fronius, jedes Mal wenn ich den PC mit ioBroker starte w.o. Fehler 979, ist nicht mehr über die IP-Adresse erreichbar, Die Batterie schaltet sich ab und ich muss den Symo hybrid, den Datenlogger und die Batterie neu starten, hab also wieder deinstalliert...... vielleicht solltest Du wieder graben ;o)

**Comment by nkleber78** [comment]
Outdated. Kann nicht reproduziert werden
