### ISSUE TITLE
Datenpunkte nur für vorhandene Messwerte

### ISSUE THREAD

**Issue by schweigel** [iobroker-community-adapters/ioBroker.fronius#61]
Die meisten Datenpunkte werden nur dann angelegt, wenn des Gerät auch die Messwerte liefert.

Aber einige werden immer angelegt, z.B. allgemeine Infodaten.

TODO:

- [ ] Datenpunkte ermitteln, die immer angelegt werden
- [ ] Abfragen einfügen, die prüfen ob Messwerte vom Gerät übermittelt werden

```
if (obj.hasOwnProperty("PVPower")) {
```

**Comment by mcm1957** [comment]
outdated
