### ISSUE TITLE
Neustrukturierung

### ISSUE THREAD

**Issue by schweigel** [iobroker-community-adapters/ioBroker.fronius#62]
Der Adapter ist sehr gewachsen und wird unübersichtlich.
Daher soll der Adapter neu strukturiert werden:

- [ ] Interpretations funktionen auslagern (ErrorCodes, DeviceTypes)
- [ ] Funktionen zum Anlegen der Datenpunkte (create...)
- [ ] Funktionen zum Auslesen der Datenpunkte (get...)

**Comment by ldittmar81** [comment]
In diesen Züge, dann wahrscheinlich die Version auf 1.2.x erhöhen, denn es sind viele Änderungen nötig. Dazu sollten nach Möglichkeit alle Bibliotheken angepasst werden.

**Comment by mcm1957** [comment]
outdated - wird ggF im Zuge der Entwicklung berücksichtigt
