### ISSUE TITLE
Add more devices

### ISSUE THREAD

**Issue by oscherer** [iobroker-community-adapters/ioBroker.fronius#63]
I have 2 Symo and 1 ohmpilot but in the setup you can only enter one IP - how can I add more devices

**Comment by nkleber78** [comment]
You need 1 instance per datamanager. If you have multiple datamanagers then you have to use for each ip an individual instance

**Comment by schweigel** [comment]
I think it should also be possible to have 2 Symo's with 1 datalogger and getting all data for both Symo with the one datalogger. It's depend on the hardware configuration.

**Comment by nkleber78** [comment]
One instance shall always relate to 1 IP address. Multiple inverters with 1 datamanager are working properly. Therefore no change is planned
