### ISSUE TITLE
mit 1.1.0 PAC keine 0 Watt bei 0 Erzeugung

### ISSUE THREAD

**Issue by Negalein** [iobroker-community-adapters/ioBroker.fronius#87]
Mit der Version 1.1.0 komme ich auch bei Dunkelheit nicht mehr auf 0 Watt Erzeugung.

Der Inverter-Datenpunkt fronius.0.inverter.1.PAC zeigt bei mir dann immer noch zB 33 Watt an.

Wir haben einen Symo 10.0-3-M

Erst mit 1.0.5 wird fronius.0.inverter.1.PAC bei keiner Erzeugung (zB bei Nacht) wieder 0 Watt angezeigt.

**Comment by nkleber78** [comment]
Ich nehme an dass dein Inverter in den sleep mode geht. Wenn das geschieht wenn der vorherige Datenpunkt noch eine Leistung hatte, dann kann es sein dass der letzte Wert erhalten bleibt. Was hast du für eine Abfrageinterval eingestellt?

**Comment by Negalein** [comment]
Nein, geht nicht in den Sleep Mode.

Abfrageintervall sind 30 Sek.

![Screenshot_2021-02-13 objects - ioBroker(1)](https://user-images.githubusercontent.com/45309436/107858643-5a2aab80-6e35-11eb-8423-d8c9a4ade912.png)

**Comment by nkleber78** [comment]
Aber hier ist der Datenpunkt ja 0... Bitte schau dir mal an in welchem Zustand das genau passiert. Und wenn das auftritt. Dann schau mal was bei dir die API hier liefert "http://ip_des_inverters/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData"

**Comment by Negalein** [comment]
Ja, weil es mit 1.0.5 (läuft aktuell bei mir) funktioniert, aber mit 1.1.0 nicht.

Bin nicht allein mit dem Phänomen.
https://forum.iobroker.net/topic/33809/fronius-adapter-entwicklung-eingestellt/238?_=1613081208863

**Comment by nkleber78** [comment]
Alles klar, aber das Forum kann nur helfen wenn auch details über das Problem bekannt sind. Das kann ein Verhalten eines spezifischen WR sein usw. Somit bitte um details damit das Problem eingegrenzt werden kann. Bei mir taucht das Problem nicht auf beim Symo Gen24...

**Comment by Negalein** [comment]
haben den Symo 10.0-3-M

welche Daten kann ich dir noch schicken?

**Comment by nkleber78** [comment]
Bitte schick mir die Daten von der API wie im vorigen Post geschrieben. Vielleicht hilft das weiter... Weiters wäre noch interessant wie der status von Fronius.0.info.connection ist. Ist dieser status true oder false? Nicht zu vergessen bitte mal den Adapter auf debug schalten und schauen was er da so alles ausspuckt. Wir versuchen möglichst sinnvolle debug messages einzubauen damit wir fehler lokalisieren können

**Comment by Negalein** [comment]
fronius.0.info.connection = true

Debug schick ich morgen. Da tut sich etwas mehr als in der Nacht! ;)

API:
{
   "Body" : {
      "Data" : {
         "DAY_ENERGY" : {
            "Unit" : "Wh",
            "Value" : 1391
         },
         "DeviceStatus" : {
            "ErrorCode" : 0,
            "LEDColor" : 3,
            "LEDState" : 0,
            "MgmtTimerRemainingTime" : -1,
            "StateToReset" : false,
            "StatusCode" : 2
         },
         "TOTAL_ENERGY" : {
            "Unit" : "Wh",
            "Value" : 50745600
         },
         "YEAR_ENERGY" : {
            "Unit" : "Wh",
            "Value" : 87658
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DataCollection" : "CommonInverterData",
         "DeviceClass" : "Inverter",
         "DeviceId" : "1",
         "Scope" : "Device"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2021-02-13T22:15:51+01:00"
   }
}

**Comment by nkleber78** [comment]
Hallo @Negalein 
was man hier sieht ist dass der Inverter den Datenpunkt nicht mehr liefert. Somit wird der Wert nicht mehr verändert. Da sich die Struktur verändert hat, damit es auch mit den unterschiedlichen Inverter Typen funktioniert, wird die Struktur dynamisch gefüllt und nur die Daten die auch auf der API verfügbar sind werden in der Struktur upgedated. Das ist mit einfachen Mitteln nicht sinnvol lösbar. Gibt es bei dir ein Problem wenn der letzte wert stehen bleibt?

**Comment by Negalein** [comment]
Ok, dann bleibt mir nur übrig auf der 1.0.5 zu bleiben.

>Gibt es bei dir ein Problem wenn der letzte wert stehen bleibt?

Ja, da der Wert dann bis zur Änderung in Grafana auch so bleibt. Oder in Sourceanalytic, usw.

**Comment by Negalein** [comment]
Hallo

Der Debug-Log sagt nicht viel aus.
Nur die normalen Ping
>04:27:56.650  - [34mdebug[39m: fronius.0 (6825) System command: /bin/ping -n -w 2 -c 1 10.0.1.90

und 3x war dieses
>04:28:01.270  - [33mwarn[39m: fronius.0 (6825) TypeError: Cannot read property 'Value' of undefined

Soll ich den Debug mal mit 1.1.1 machen?

**Comment by nkleber78** [comment]
Installier mal die Variante von Github aus meinem Repository und gib mir dann Bescheid ob deine Probleme damit gelöst sind...
https://github.com/nkleber78/ioBroker.fronius

Diese Variante dann mal im Debug modus laufen lassen. Dann solltest du auch entsprechende log Einträge sehen...

**Comment by Negalein** [comment]
>Installier mal die Variante von Github aus meinem Repository und gib mir dann Bescheid ob deine Probleme damit gelöst sind...

Ja, mit 1.1.2 zeigt es wieder 0 an! 
Danke
