### ISSUE TITLE
(Gelöst) Konfiguraton nicht mehr möglich seit 1.1.3

### ISSUE THREAD

**Issue by Dreistein19** [iobroker-community-adapters/ioBroker.fronius#98]
Seit dem Update auf 1.1.3 sind die Felder für die IP Adresse und die Abfragezeiten "grau"
Im Logfile kommt die Fehlermeldung :

fronius.0 | 2021-03-17 17:19:27.873 | error | (12990) Please configure the Fronius adapter
-- | -- | -- | --

**Comment by nkleber78** [comment]
Das kann ich bei mir nicht reproduzieren... Auch wenn ich eine neue Instanz anlege werden die Felder bei mir korrekt angezeigt. Hast du neu installiert oder ein Update von z.b. 1.1.0 gemacht?

**Comment by Dreistein19** [comment]
Ja.
Danke für deine schnelle Rückmeldung.
Dann muss der Fehler ja bei mir sein. Leider keine Ahnung was da los. ist.
Bitte noch ein paar Tage offen lassen. Vielleicht finde ich ja eine Lösung.

**Comment by Dreistein19** [comment]
Moin,

was habe ich gemacht: 
- Fronius Adapter gestoppt
- ioBroker gestoppt
- Versucht die Config datei händisch zu ändern. Misserfolg, Rechte Problem.
- ioBroker Reparatur-Script gestartet.
- ioBroker gestartet
- kein Erfolg, Felder Grau.
- Fronius Adapter komplett gelöscht. (Das war ein riesen Fehler. Siehe Unten.)
- ioBroker neu gestartet.
- Fronius Adapter neu Installiert.(1.1.3)
- Erfolg Felder nun editierbar.
ABER  : 
Nachdem dem Anlegen aller neuen Objekte sind diese mit der Vorherigen Version nicht mehr Kompatibel.
Es fehlen z.b. sämtliche AC Werte wie z.b. PAC. Spannung u.s.w.
Es werden nun 2 Inverter angelegt. 0 und 1. Es gibt aber nur einen Primus 4.x.

Alles in allem war das Update für mich ein Fehler.
 
Ursache unbekannt, kann geschlossen werden.
Danke.

**Comment by nkleber78** [comment]
@Dreistein19 Schade dass es bei dir so viele Probleme gemacht hat! Kannst du vielleicht noch prüfen was bei dir in der Adapter config bzgl der inverter drin steht? (system.adapter.fronius.0)
Falls da 0 und 1 drin steht, dann bitte mal den eintrag für die Inverter löschen, in die Adapter config gehen und "ip prüfen" drücken. Dann nochmals schauen was im inverter feld steht. Das wäre wichtig zu wissen damit ich das ggf. fixen kann wenn hier was nicht passt

**Comment by Dreistein19** [comment]
Wie geschrieben, ich komme nicht an die Datei. Linux klopft mir auf den Finger.
Mein Wissen bei Linux reicht dafür nicht.
Unten nun die Config , die man unter instanzen-> fronius.0 abspeichern kann. Bevor folgendes gemacht wurde : 
 - Inverter.0 gelöscht
 - Adapter neu gestartet
 - "IP-Adresse..."  Button gedrückt.
 - Inverter.0 wieder da
 - Inverter.0 gelöscht
 - "IP-Adresse.." Button gedrückt
 - Erfolg : Inverter.0 bleibt weg ! ALLE ! Werter wieder da. Auch PAC.
Was auch immer da geklemmt hat, es gibt scheinbar Digitales WD 40 :)
Vielleicht müsste man den Button zusätzlich beschriften.
So was wie "IP-Adresse überprüfen und Objekte Aktualisieren" z.B.

`{
  "_id": "system.adapter.fronius.0",
  "common": {
    "name": "fronius",
    "version": "1.1.3",
    "title": "Fronius inverter",
    "license": "MIT",
    "authors": [
      "ldittmar <iobroker@lmdsoft.de>",
      "nkleber78",
      "schweigel"
    ],
    "compact": true,
    "platform": "Javascript/Node.js",
    "mode": "daemon",
    "icon": "fronius.png",
    "materialize": true,
    "enabled": true,
    "messagebox": true,
    "extIcon": "https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.fronius/master/admin/fronius.png",
    "keywords": [
      "Fronius",
      "inverter",
      "Wechselrichter",
      "hybrid",
      "Symo"
    ],
    "readme": "https://github.com/iobroker-community-adapters/ioBroker.fronius/blob/master/README.md",
    "loglevel": "info",
    "type": "energy",
    "connectionType": "local",
    "dataSource": "poll",
    "installedFrom": "iobroker-community-adapters/ioBroker.fronius#master",
    "installedVersion": "1.1.3",
    "host": "RP4-ioBroker"
  },
  "native": {
    "baseurl": "/solar_api/v1/",
    "apiversion": "1",
    "inverter": "",
    "sensorCard": "",
    "stringControl": "",
    "meter": "",
    "storage": "",
    "ip": "192.168.18.26",
    "poll": "12",
    "pollarchive": "12"
  }
}`

**Comment by m4ding** [comment]
gib in der konsole mal "sudo su" (ohne Hochkommata) ein, damit hast du root Rechte (vorausgesetzt dein User ist in der entsprechenden Gruppe oder du hast das root pw).

**Comment by nkleber78** [comment]
@Dreistein19 Hast du einen GEN24? Wenn ja, dann ist es leider so dass die API da Fehlerhaft ist und der Inverter nicht erkannt wird. Dabei habe ich den default auf 0 gestellt. Bei dir ist nämlich im Objekt bei Inverter auch nichts drin... D.h. wenn später dann die ID 1 eingestellt wird dann nimmt er das. 
Bzgl. fehlender Werte: Wenn der WR im Standby ist bekommst du nicht alle Objekte über die API, daher kann es sein dass du ggf. am Anfang nicht alle Objekte hast...

**Comment by Dreistein19** [comment]
Ich habe keine GEN24 sondern einen Primo 4.x
Das kann natürlich sein, daß ich einfach das Pech hatte, das mitten in dem Chaos auch noch der Wechselrichter offline gegangen ist.
Morphys Law ....
Aber beim Update des Adapters müsste er noch Online gewesen sein ...

Nochmals vielen Dank für deine (eure) Geduld und Hilfe.

**Comment by mcm1957** [comment]
Falls hier noch etwas offen ist, bitte neuen Issue erstellen (mit Angabe der derzeit verwendeten Adapter und Geräteversionen.
